### ISSUE TITLE
subtitles arent embed

### ISSUE THREAD

**Issue by thaynos** [jely2002/youtube-dl-gui#100]
subtitles arent embed anymore
they were there when i downloaded videos using v2.1.0
although at the time there was an issue in which it embed subititles of EVERY single language
so it was a pain in the ass to search for the english subtitle
but now its even worse as theres no subtitle at all.

**Comment by jely2002** [comment]
Hi there, I am unable to replicate this issue when opening the downloaded video in the latest version of VLC.  What app are you using to open the downloaded video?

**Comment by thaynos** [comment]
how do i choose? i dont see any option relating subtitles in the options menu.

**Comment by jely2002** [comment]
![image](https://user-images.githubusercontent.com/20154900/121380961-9b474e00-c945-11eb-9e43-9fdc9167b9e6.png)
First you click on the subtitle icon. This will open the subtitle settings menu for that video/playlist.

![image](https://user-images.githubusercontent.com/20154900/121381090-b2863b80-c945-11eb-9271-b1c204fbcd17.png)
Here you can select which subtitles or auto generated captions to download. When clicking `ok` the changes get applied and it will embed your selected subtitles.

**Comment by thaynos** [comment]
oh ok so sorry for the inconvenience i usually just set the subtitles using the icon at the bottom rather on the playlist. coud you add an option so that you can change the subtitles globally for all videos? also an option to choose download subtitle by default and default language too.

**Comment by thaynos** [comment]
it works perfectly now thank you for your help
