### ISSUE TITLE
Shortcuts

### ISSUE THREAD

**Issue by MildPanda** [jely2002/youtube-dl-gui#101]
Add 2 shortcuts to allow downloading URL in clipboard either video with audio or just audio.

**Comment by jely2002** [comment]
Do you have an idea as to what keys you need to press to activate the shortcut?

**Comment by MildPanda** [comment]
As an example I had made a AHK script that had broke but prior I was using Ctrl + Shift + V to download the video and Ctrl + Shift + M to just download music. Unsure how much more effort this would be but perhaps this could be coded to be a customizable shortcut too so people that don't like the keys can change them.

**Comment by jely2002** [comment]
I think I will start with adding hardcoded shortcuts. Then sometime I can create a settings section where you can customize all shortcuts,

**Comment by jely2002** [comment]
This is now added in v2.2.2.

Adding a copied video link to the queue:
`Ctrl/Cmd+Shift+V`

Downloading all videos in the queue:
`Ctrl/Cmd+Shift+D`
