### ISSUE TITLE
Open Source Get Cookies Extensions for Chromium and Firefox Browsers?

### ISSUE THREAD

**Issue by trymeouteh** [jely2002/youtube-dl-gui#102]
Is there any extensions for getting cookies for Chrome, Brave and Firefox? In this wiki tutorial I cannot confirm if these extensions listed are open source.

https://github.com/jely2002/youtube-dl-gui/wiki/Tutorial:-Private-videos-&-playlists

**Comment by jely2002** [comment]
Hi trymeouteh,

As far as I know there are no open source browser extensions that get cookies.
If I ever find time, I might create one since you brought it up :)

Closing the issue as there isn't much more to discuss.
