### ISSUE TITLE
Pause Button

### ISSUE THREAD

**Issue by Fanboy-Studios** [jely2002/youtube-dl-gui#104]
**Is your feature request related to a problem? Please describe.**

I hate not being able to pause the downloads. This can be problematic especially if you have slow internet like I do.

**Describe the solution you'd like**

A pause button. Pretty simple, click it and it pauses the download. 

**Describe alternatives you've considered**

I had used YouTube-DGL in the past, but it doesn't seem to work anymore now. So, here I am! :)

**Additional context**

**Comment by jely2002** [comment]
Hi Fanboy-Studios,

If you cancel a video (remove it by clicking on the cross) it will stop downloading the video. It however keeps the part it has already downloaded. So if you re-add the video it should start from where it was left off.

I think adding a pause button further clutters the UI. And that should be avoided, especially if the requested behavior (stop/restart) downloads can already be achieved by removing and then re-adding the video.

Thanks for understanding.
