### ISSUE TITLE
Globally listens for Dev Tools Inspector shortcut (Ctrl + Shift + I)

### ISSUE THREAD

**Issue by Aankhen** [jely2002/youtube-dl-gui#106]
**Describe the bug**
The Chrome Dev Tools shortcut <kbd><kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd></kbd> in any application triggers the Electron Dev Tools in youtube-dl-gui.

**To Reproduce**
1. Open youtube-dl-gui
2. Open a Chrome window
3. Press <kbd><kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd></kbd>

**Expected behavior**
Nothing in youtube-dl-gui.

**Screenshots**
You may have to follow the link to see the full GIF: ![The inspector in youtube-dl-gui opens when pressing Ctrl+Shift+I elsewhere](https://user-images.githubusercontent.com/978992/122112917-0493f900-ce3f-11eb-8b23-9736c18f2490.gif)

**Additional info (please complete the following information):**
 - OS: Windows 10
 - Application version: 2.2.1

**Additional context**
I demonstrated this with Chrome by opening a new window after starting youtube-dl-gui, but it doesn’t seem to be restricted to Chrome, so I think it’s listening globally.

**Comment by jely2002** [comment]
Hi Aankhen,'

This has been fixed now, and will be released in the first bugfix or feature update.

Closing this. If you have any more questions feel free to ask.

**Comment by Aankhen** [comment]
Great! Thank you very much for the speedy response.
