### ISSUE TITLE
No choice of audio format in settings

### ISSUE THREAD

**Issue by A-Cyr** [jely2002/youtube-dl-gui#107]
I mostly download playlists in Audio Only mode. Your GUI save sound in mp3 format, while youtube-dl saves the same playlist in m4a and opus formats.

The paradox is that in both cases the --bestaudio option is used ((

Please add format choice option to your GUI.

**Comment by jely2002** [comment]
Hi A-Cyr,
I have now added a setting where you can select what format you want to use for audio-only downloads.
It will be available on the next release.

Closing the issue, as this will be resolved next release.
