### ISSUE TITLE
Download location keeps resetting

### ISSUE THREAD

**Issue by Aankhen** [jely2002/youtube-dl-gui#109]
**Describe the bug**
Every time I start youtube-dl-gui, the download location is reset to the Downloads folder instead of the folder I selected.

**To Reproduce**
1. Start youtube-dl-gui.
2. Set a custom download location.
3. Restart youtube-dl-gui.

**Expected behavior**
The download location is persisted between invocations.

**Additional info (please complete the following information):**
 - OS: Windows 10
 - Application version: 2.2.1

**Comment by jely2002** [comment]
Hi Aankhen,

This isn't a bug. It is intentional that the location isn't persisted. Although I agree that it should save the location. 
Will add this feature soon.

**Comment by Aankhen** [comment]
Oh, I see! Sorry about that. For some reason I thought it was previously persisting the location but not now. It would be great to have this feature, anyway.

**Comment by jely2002** [comment]
This feature has now been added. It will be released with the next version.
Closing this for now.

**Comment by Aankhen** [comment]
Thanks very much!
