### ISSUE TITLE
Error: You are being ratelimited by the service.

### ISSUE THREAD

**Issue by cy920820** [jely2002/youtube-dl-gui#110]
Error! Too many requests (429). 

Please help to answer

**Comment by jely2002** [comment]
Hi cy920820,
If you have questions about certain errors, please take a look at the [errors wiki page](https://github.com/jely2002/youtube-dl-gui/wiki/Errors). Most of the common issues are explained there.
Here's a copy paste of the explanation:

## Too many requests (429)
**Trigger**: `HTTP Error 429`

**Cause**: 
The service has soft banned or ratelimited you. This can happen when you download too much videos in a short time. The ban usually lasts for no longer than 24 hours.

**Solution**: Wait for the ban to expire and take it easy next time. If you have a VPN you can also use this to circumvent the ban, although this is not recommended. After all you were softbanned/ratelimited with a reason.

If you have a follow up question, feel free to ask.

**Comment by cy920820** [comment]
> Hi cy920820,
> If you have questions about certain errors, please take a look at the [errors wiki page](https://github.com/jely2002/youtube-dl-gui/wiki/Errors). Most of the common issues are explained there.
> Here's a copy paste of the explanation:
> 
> ## Too many requests (429)
> **Trigger**: `HTTP Error 429`
> 
> **Cause**:
> The service has soft banned or ratelimited you. This can happen when you download too much videos in a short time. The ban usually lasts for no longer than 24 hours.
> 
> **Solution**: Wait for the ban to expire and take it easy next time. If you have a VPN you can also use this to circumvent the ban, although this is not recommended. After all you were softbanned/ratelimited with a reason.
> 
> If you have a follow up question, feel free to ask.

Thanks bro [啤酒]
