### ISSUE TITLE
bulk download option from other websites and custom name support

### ISSUE THREAD

**Issue by patricktow** [jely2002/youtube-dl-gui#112]
**Is your feature request related to a problem? Please describe.**
feature request : 1) adding support to download videos in bulk from (m3u8 urls) that is inserted inside a file that have the urls and their custom video names (a .csv/txt file) to bulk download them one by one or more automatically rather than inserting in the application one link after the other and then pressing the download button for each one which is a bit slow process
the .csv/txt file for example having support to have video names and urls  and having urls only in the .csv/txt file incase their is no name issue which is in number 2),3) request below 
the list.csv file example
video1name , url of video 1
video2name , url of video 2
for example  : the list file will be loaded in the gui app and then having the urls with their custom names that is set in that file to be added in queue list and then be downloaded automatically one by one or more than one  
something like this  for .csv file : https://github.com/changh95/video-scraper 
2) some website having the videos being downloaded to be having the same name for example video1  name is cat.mp4 and another video2 name is cat.mp4 too (different videos but having same name) which will lead to video2 to appear as to be downloaded but its not downloaded its video1 which having same name made the app to think that video2 got downloaded bec of the same name (i have added this in the file format [%(epoch)s.%(ext)s](https://www.reddit.com/r/youtubedl/comments/jtczho/how_to_make_a_batch_with_renamed_titles_from_m3u8/) to bypass the overwriting but still not a great option since files will have to be renamed again to be better than a random number, having  an option in the settings to not allow overwriting of files having same name would be great
3) adding support to edit file names before downloading by double clicking on the title so that name will be set on the final processed file and/or a filename field that can be activated on the settings and appear below the url insertion field before going on the queue list
thanks for that great gui software that support youtube-dl and having a beautiful UI in it :)

**Comment by jely2002** [comment]
Closing this one in favour of: #269 and #282.
