### ISSUE TITLE
Queue - Drag and Drop

### ISSUE THREAD

**Issue by rogerwindberg** [jely2002/youtube-dl-gui#115]
It's too bad to add multiple videos to the Download queue and not be able to choose which one to download first.

I would love to be able to organize the Download queue to download the videos in the order I select.

I recommend adding a "drag and drop" system to verfically organize the Download queue so that it starts with the first and ends with the last.

Example:

![example](https://user-images.githubusercontent.com/69870624/123121466-8fff2280-d41b-11eb-9af7-97193b7c71c1.gif)

**Comment by jely2002** [comment]
This feature has been implemented.  It will be released with version 2.3.0.
Below a demo of dragging cards:

https://user-images.githubusercontent.com/20154900/128018944-eebb0e1d-9035-40af-a15c-254ceffce091.mp4
