### ISSUE TITLE
Incorporate IDM system

### ISSUE THREAD

**Issue by rogerwindberg** [jely2002/youtube-dl-gui#118]
I have a suggestion to improve the YouTube DL GUI:

- Incorporate in it the "IDM" (Internet Download Manager) system that you have in [FireDM](https://github.com/firedm/FireDM). In this way, in addition to being able to perform YouTube Downloads, we can make the most of our internet connection to increase the Download speed! :D

**Comment by jely2002** [comment]
I will not be adding IDM to this application. As it would require a major rewrite, and is not in the scope of my goals with this application.

Thanks for understanding.
And feel free to use FireDM if it fits your needs better!
