### ISSUE TITLE
Can't download video's

### ISSUE THREAD

**Issue by DutchEclipse** [jely2002/youtube-dl-gui#120]
**Describe the bug**
Getting a error when trying to download a youtube video called "You are being ratelimited by the service."

**To Reproduce**
1. Copy a youtube link
2. Add it to the qeueue
3. Click the download button

**Expected behavior**
The video should download.

**Screenshots**
![image](https://user-images.githubusercontent.com/83969413/124350668-399d9b00-dbf6-11eb-928f-bcb1a9a25b1a.png)

**Additional info (please complete the following information):**
 - OS: Windows 10 Pro 21h1
 - Application Version: 2.2.1
 
 **Other**
 
 This has been happening for a week now.

**Comment by jely2002** [comment]
Trigger: HTTP Error 429

Cause: The service has soft banned or ratelimited you. This can happen when you download too much videos in a short time. The ban usually lasts for no longer than 24 hours.

Solution: Wait for the ban to expire and take it easy next time. If you have a VPN you can also use this to circumvent the ban, although this is not recommended. After all you were softbanned/ratelimited with a reason.

----

This is the description this error has on the error wiki page.
Your IP may be (soft)banned by YouTube. There's nothing I can do from within the app to prevent this from happening.

Thank you for understanding.
