### ISSUE TITLE
"send to yt-dl-gui" browser extension

### ISSUE THREAD

**Issue by EricE549X** [jely2002/youtube-dl-gui#121]
so before i found this app, i used another app called itubedownloader, which has now been discontinued. one of my favorite features from itubedownloader was that you could integrate it with safari, which means it comes with an extension that allows you to click a button on the top bar to send a video to itubedownloader to download it. it'd be useful because you wouldn't have to open yt-dl-gui every time you wanna download a video because you can click the button and it automatically opens yt-dl-gui, then the video would be ready to download.

**Comment by jely2002** [comment]
Hi Eric,

I definitely like the idea of a browser extension. I could make one for Chrome, but not for safari. As this requires me to be a member of the Apple developer program ($99/year). Right now I don't have the time to work on a browser extension for Chrome, but I will definitely keep the idea in mind.

Thanks for understanding.
