### ISSUE TITLE
Add to Windows Store

### ISSUE THREAD

**Issue by gkkirilov** [jely2002/youtube-dl-gui#122]
**Is your feature request related to a problem? Please describe.**
I hate seeing shitty and paid youtube downloaders in the Microsoft store and this great one not be there

**Describe the solution you'd like**
Add youtube-dl-gui to the Windows Store

**Comment by jely2002** [comment]
Hi there!

I have submitted this app to the Microsoft store. As I think it's a great way to reach more users. The submission is currently awaiting approval.

Will keep this issue updated.
If you have any more questions, feel free to ask.

**Comment by jely2002** [comment]
The app has been published on the Microsoft Store. 🥳 

https://www.microsoft.com/en-us/p/open-video-downloader/9p53s4t9znj5
