### ISSUE TITLE
Video/Audio Trimming 

### ISSUE THREAD

**Issue by gplgps** [jely2002/youtube-dl-gui#123]
**Is your feature request related to a problem? Please describe.**
I'd like to have a possibility to trim the video after the download with FFMPEG within the app. This could save some time later by not have to trim it seperately.

**Describe the solution you'd like**
I would like to add the possibility to set the start and/or finish time(s) of a video/audio so that FFMPEG could handle it afterwards.

**Additional context**
One issue I currently see is that I can't find a suitable position for this option in the UI.

**Comment by jely2002** [comment]
Hi gplgps,

I agree with you it would be a great addition to the app. However, as you stated yourself there isn't really a good place in the UI for it. Another issue is that it takes away from the original scope of the app, download videos. There are much better applications for cutting videos, I can try making my own implementation. But it will most likely be inferior to something like handbrake.

This is why I will not be implementing this feature at this time. Thank you for understanding.
If you have any more questions feel free to ask them.
