### ISSUE TITLE
Vimeo downloads not working

### ISSUE THREAD

**Issue by Aankhen** [jely2002/youtube-dl-gui#125]
**Describe the bug**
Vimeo downloads are returning a 403:
![](https://user-images.githubusercontent.com/978992/124558322-18d48000-de58-11eb-8a41-105a8b9fecc4.png)
When I try youtube-dl directly, it does show the 403, but only for the metadata. After that, it continues to download the video:
```text
[vimeo] 568428658: Downloading webpage
[vimeo] 568428658: Downloading JSON metadata
[vimeo] 568428658: Downloading JSON metadata
WARNING: Unable to download JSON metadata: HTTP Error 403: Forbidden
[vimeo] 568428658: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 568428658: Downloading akfire_interconnect_quic m3u8 information
[vimeo] 568428658: Downloading fastly_skyfire m3u8 information
[vimeo] 568428658: Downloading fastly_skyfire m3u8 information
[vimeo] 568428658: Downloading akfire_interconnect_quic MPD information
[vimeo] 568428658: Downloading akfire_interconnect_quic MPD information
[vimeo] 568428658: Downloading fastly_skyfire MPD information
[vimeo] 568428658: Downloading fastly_skyfire MPD information
[dashsegments] Total fragments: 6
[download] Destination: Mr. Kaplin\LEGO - Vehicles with a bit extra. 30 sec - Cars, trucks, planes..fdash-fastly_skyfire_sep-video-5b8e896c.mp4
[download] 100% of 17.32MiB in 00:05
[download] Mr. Kaplin\LEGO - Vehicles with a bit extra. 30 sec - Cars, trucks, planes..fdash-fastly_skyfire_sep-audio-884716f8.m4a has already been downloaded
[download] 100% of 935.40KiB
[ffmpeg] Merging formats into "Mr. Kaplin\LEGO - Vehicles with a bit extra. 30 sec - Cars, trucks, planes..mp4"
Deleting original file Mr. Kaplin\LEGO - Vehicles with a bit extra. 30 sec - Cars, trucks, planes..fdash-fastly_skyfire_sep-video-5b8e896c.mp4 (pass -k to keep)
Deleting original file Mr. Kaplin\LEGO - Vehicles with a bit extra. 30 sec - Cars, trucks, planes..fdash-fastly_skyfire_sep-audio-884716f8.m4a (pass -k to keep)
[ffmpeg] Adding metadata to 'Mr. Kaplin\LEGO - Vehicles with a bit extra. 30 sec - Cars, trucks, planes..mp4'
```

**To Reproduce**
1. Enter Vimeo URL (e.g. <https://vimeo.com/568428658>).
2. Click on +.
3. Click on download icon.

**Expected behavior**
The Vimeo video is downloaded.

**Additional info (please complete the following information):**
 - OS: Windows 10
 - Application version: 2.2.2

**Additional context**
I think this only started in the past 48 hours, so something must have changed on Vimeo’s end, but fortunately youtube-dl can handle it (and seems to be able to fetch metadata anyway, because the video file has the description and uploader, at least).

EDIT:
I confirmed that youtube-dl-gui is using the same version of youtube-dl (2021.06.06) as the one I tried separately.

**Comment by jely2002** [comment]
This should now be fixed. It will be deployed on the next bug/feature update.
Closing this for now.
