### ISSUE TITLE
Attempting to open downloaded audio files opens the wrong filename

### ISSUE THREAD

**Issue by were491** [jely2002/youtube-dl-gui#126]
**Describe the bug**
Opening a downloaded non-mp4 file (such as the mp3 from [this video](https://www.youtube.com/watch?v=w8ypYC9YHbM)) from the application will attempt to open the file with extension mp4 rather than the correct extension, and the filename is also incorrect.

**To Reproduce**
1. Download a Youtube video (ex.: https://www.youtube.com/watch?v=w8ypYC9YHbM) as "Audio only". This happens regardless if the "Audio only" option was selected in the bottom of the main interface or for the specific video.
2. Click on "Open file".

**Expected behavior**
The file should be opened with the correct extension, in this case mp3, and with the correct filename.

**Screenshots**
![YouTube_Downloader_GUI_v7gIkohDRq](https://user-images.githubusercontent.com/34976611/124781337-f0588e80-df08-11eb-9a86-b0132c6aac8f.png)

The downloaded file was **actually** named "they shmoove-(p).mp3"

**Additional info (please complete the following information):**
 - OS: Windows 10 21H1
 - Application version 2.2.2

**Comment by were491** [comment]
I think it may just be that you forgot a closing parenthesis in line 358 of modules/QueryManager.js, which is `fs.readdir(video.downloadedPath, (err, files) => {`

**Comment by jely2002** [comment]
This is now fixed. The fix will be visible on the next bug/feature release. Closing this for now.
