### ISSUE TITLE
Error with youtube link

### ISSUE THREAD

**Issue by mrmmg** [jely2002/youtube-dl-gui#129]
**Describe the bug**
Please see screenshot

**To Reproduce**
1. paste the youtube link and click on the plus button
2. See an error

**Screenshots**
![image](https://user-images.githubusercontent.com/30490118/125142905-29be1380-e12e-11eb-8f75-db997d7ea20d.png)

**Additional info (please complete the following information):**
 - OS: Windows 10 - 64bit
 - Application version: 2.2.2

**Comment by jely2002** [comment]
Hi mrmmg,

Does this happen to you for every video or only sometimes?

I have only seen this error once when I was testing some stuff for the Microsoft store release. It means something is wrong with python or the youtube-dl executable, I was unable to determine what caused the error at that time.
