### ISSUE TITLE
Change visible names to Open Video Downloader

### ISSUE THREAD

**Issue by jely2002** [jely2002/youtube-dl-gui#130]
All visible names in the app must be changed to `Open Video Downloader`. This will be the new visible name of the application. The repo will still be called youtube-dl-gui as changing that will mess up auto updating. As well as the package name.

**Comment by jely2002** [comment]
This name change is required in order to submit this app to the microsoft store. As YouTube is a trademarked name. #122

**Comment by thaynos** [comment]
it sounds a but generic but at least its getting on the ms store :D

**Comment by jely2002** [comment]
Closing this as the name change has been applied. (Code wise)
