### ISSUE TITLE
prefix index title for download playlist vidoes

### ISSUE THREAD

**Issue by hdriel** [jely2002/youtube-dl-gui#131]
**Adding index to filename downloaded for playlist** 
sometime we want to download youtube playlist, but the order is matter, 
so, please add a toggle or in other way to allow add index as prefix to the filename. 

Thanks a lot, great repo!

**Comment by jely2002** [comment]
You can create your own file output formats, by using the filename format setting.

![image](https://user-images.githubusercontent.com/20154900/125609174-cb74f632-622a-4188-ae47-bc1f69ab7d35.png)

So if you want to prefix a video name with the index in the playlist you would do: `%(playlist_index)-%(title)s.%(ext)s`

For documentation on this please check youtube-dl.

If you have any other questions feel free to ask them. Closing this issue for now.
