### ISSUE TITLE
logs viewer

### ISSUE THREAD

**Issue by thaynos** [jely2002/youtube-dl-gui#132]
i would like a logs viewer to see whats happening within the app as sometimes the app just stops working and clicking anywhere on the app shows selecting cursor but nothing gets slected. but in task manager it shows the app/ ffmpeg taking lot of disk bandwidth.

**Comment by jely2002** [comment]
Hi thaynos,

I have added a download log. It can be saved as a file afterwards as well.
![image](https://user-images.githubusercontent.com/20154900/128007753-11d66108-668a-49be-82b7-3ca46cc2ad01.png)

You access the log by clicking on the textbook. The download button gets replaced with the textbook button when you start the download.
![image](https://user-images.githubusercontent.com/20154900/128007895-8646e5e1-22cc-4c00-8ac3-657d7e9780b0.png)

If you have any questions regarding this, please let me know.

**Comment by thaynos** [comment]
thank you for adding this feature!
