### ISSUE TITLE
pause downloads feature

### ISSUE THREAD

**Issue by thaynos** [jely2002/youtube-dl-gui#133]
as it says in title

**Comment by jely2002** [comment]
Hi thaynos,

This feature request has been created before (#104, #30). I have closed it then for the following reason.

If you cancel a video (remove it by clicking on the cross) it will stop downloading the video. It however keeps the part it has already downloaded. So if you re-add the video it should start from where it was left off.

I think adding a pause button further clutters the UI. And that should be avoided, especially if the requested behavior (stop/restart) downloads can already be achieved by removing and then re-adding the video.

Thanks for understanding.

**Comment by thaynos** [comment]
this doesnt happen it just creates a duplicate video either with .temp in it or a different quality

**Comment by KygekDev** [comment]
> Hi thaynos,
> 
> This feature request has been created before (#104, #30). I have closed it then for the following reason.
> 
> If you cancel a video (remove it by clicking on the cross) it will stop downloading the video. It however keeps the part it has already downloaded. So if you re-add the video it should start from where it was left off.
> 
> I think adding a pause button further clutters the UI. And that should be avoided, especially if the requested behavior (stop/restart) downloads can already be achieved by removing and then re-adding the video.
> 
> Thanks for understanding.

Thanks for your reply, but what if someone downloads videos from a playlist then cancels one of the video from the queue? It would be a pain to restore the video back to the queue.
