### ISSUE TITLE
app randomly stops working

### ISSUE THREAD

**Issue by thaynos** [jely2002/youtube-dl-gui#135]
what it says in title
this has happened a couple of times
its stuck on 23/85
![image](https://user-images.githubusercontent.com/83282129/125514605-c8c42ccc-6d9e-46dd-9d4f-b152b4703f37.png)

**Comment by thaynos** [comment]
ok it never works at this point ive tried restarting and re downloading a couple of times nothing works. its stuck on 6/100 :(
![image](https://user-images.githubusercontent.com/83282129/125588700-60f68dd7-5c84-4c8f-87ff-f7b13ebc6fb6.png)

**Comment by jely2002** [comment]
Can you click on the 'console' tab in the dev tools for me. Now it just shows my code, while I need the log.

**Comment by jely2002** [comment]
It most likely isn't stuck, but it's just taking a whole lot longer because youtube is throttling the connection.

**Comment by thaynos** [comment]
[image: image.png]

**Comment by thaynos** [comment]
![image](https://user-images.githubusercontent.com/83282129/125623152-41b60640-e9fc-4c8f-8733-cdd4168c89c0.png)
i tried to change simuntaneous downloads setting and this came

**Comment by thaynos** [comment]
i have a feeling that it is youtube that is network throttling like you said. is there any way to circumvent this throttling?

**Comment by jely2002** [comment]
I don't think youtube is throttling the download knowingly. They most likely changed something and youtube-dl sometimes doesn't play nicely. This would be something for the youtube-dl developers and not me.

Closing the issue.
