### ISSUE TITLE
Windows portable release stores settings in %AppData%\Roaming

### ISSUE THREAD

**Issue by xylltch** [jely2002/youtube-dl-gui#136]
**Describe the bug**
Windows portable release (version 2.2.2) stores configuration data in AppData/Roaming.

**To Reproduce**
1. Launch application
2. Application generates youtube-dl-gui-portable directory in AppData\Roaming
3. Download of ytdl binary generates youtube-dl-gui directory in AppData\Roaming

**Expected behavior**
Application should generate those directories in the same location where executable (YouTube-Downloader-GUI-2.2.2-portable.exe) resides.

**Additional info (please complete the following information):**
 - OS: Windows 10
 - Application version: 2.2.2
 - Application type: portable

**Additional context**
Portable applications should keep their configuration files in the same location as the executable file to ensure true portability when accessed from another location (for example when program is stored on a thumbdrive moved between computers or in a directory synced to other computers via cloud storage). Ideally the AppData directory (and any other directories other than the one where the executable is located) are not touched at all.

**Comment by jely2002** [comment]
You are absolutely right. I will make it so that the app will first try to create a new folder next to it. If it can't do that for whatever reason it will create a folder in appdata as fallback. Does this sound okay?

**Comment by xylltch** [comment]
> You are absolutely right. I will make it so that the app will first try to create a new folder next to it. If it can't do that for whatever reason it will create a folder in appdata as fallback. Does this sound okay?

Yep, absolutely, that sounds like a good approach. Thank you for considering this feedback!

**Comment by jely2002** [comment]
This feature has now been added, it will be released in upcoming version 2.3.0.
