### ISSUE TITLE
Keep audio format as source (no conversion)

### ISSUE THREAD

**Issue by ron-ytsma** [jely2002/youtube-dl-gui#137]
i see you added "Force audio-only downloads to use output format" with a dropdown in the settings, that is great.

could you add an option keep audio as source in that dropdown?

aka no conversion at all; just separate the existing audiotrack from the sourcefile
any (re-)conversion on high quality audio will reduce audio quality.
i have not seen the ability to do so in the app

love the app's useability! really nice

**Comment by NebelNidas** [comment]
What a coincidence, I just wanted to ask for the exact same feature! Because I'm looking for an option which performs this command: `youtube-dl -if "bestaudio" --extract-audio --embed-thumbnail --add-metadata`, which automatically selects the best audio format.

**Comment by jely2002** [comment]
You can keep the raw files by checking the `Keep unmerged files` setting. Does this answer your question?

**Comment by jely2002** [comment]
![image](https://user-images.githubusercontent.com/20154900/126010583-c1ff9f10-fd18-4df8-8b76-f7b43b1fba7b.png)

**Comment by ron-ytsma** [comment]
it could, but 2.5 tiny problems with that:
-it will create whatever is selected in the dropdownm which i dont want created
(and the ffmpeg transcode is lengthy and blocks the UI)
-if e.g. opus is the source audiotrack format and opus is what i selected in dropdown, will it transcode anyway? not sure what the outcome is here.
-i have to remove flurry of excess files

so i'd like to have directly what i need without having to manually sort/delete all the stuf that i am not interested in.

**Comment by jely2002** [comment]
Thanks for the contribution Julian, will see if we can merge this asap.

**Comment by jely2002** [comment]
This has now been implemented. Big thanks to @NebelNidas  for the PR! It will release with the next bugfix/feature update.

**Comment by NebelNidas** [comment]
Perfect, thank you for merging this so quickly! 😊 It was my first time working on a Node.js application, I'm happy to see it turned out well 😅

**Comment by ron-ytsma** [comment]
you guys! osom! :)
