### ISSUE TITLE
[Bug] Windows Defender is flagging the portable exe as Trojan

### ISSUE THREAD

**Issue by eredrolo** [jely2002/youtube-dl-gui#139]
**Describe the bug**
Windows Defender is flagging the portable version as Trojan (Emali.A!cl) and removing it. Defender only flags it when I open the app. Scanning the exe before opening doesn't show anything. Looks like the portable exe is downloading something which is triggering Defender.

**To Reproduce**
1. Download portable exe
2. Open it
3. Windows Defender flags it and removes it

**Expected behavior**
The app opens normally. It worked fine few days ago but it's not working now. 

**Screenshots**
![error](https://user-images.githubusercontent.com/74611933/126281252-9c88c265-bdb4-42b2-8883-6134982e3fb3.jpg)

**Additional info:**
 - OS: Windows 10 ver 2004
 - Application version: 2.2.2
 - Application type: Portable

**Comment by jely2002** [comment]
I'm currently not home. So I'm unable to verify if it happens for me too. I just find it funny that I made this app to combat those ad/virus riddled websites and now Defender flags it as a virus.

Anyway I can assure you I would never willingly put malware into this app. I think it's a false positive. When I search for the name of the trojan I find a lot of false positives.

**Comment by jely2002** [comment]
I advise you to run a full system scan with something like malwarebytes. As the trojan might have already been on your system and injected itself into youtube-dl-gui, triggering Defender. I don't think this is the case but never too sure.

**Comment by admk** [comment]
I am encoutering this too possibly as a result of recent defender update.

**Comment by jely2002** [comment]
I will submit the app to the Windows Defender team when I get home. Does the installer get flagged as well by Defender?

**Comment by eredrolo** [comment]
@jely2002 The installer is working fine. Defender is only flagging the portable version.

I also ran a full system scan with both Malwarebytes and Defender and they didn't show any infections on the system.

**Comment by jely2002** [comment]
@eredrolo Can you give me the defender definitions version? https://go.microsoft.com/fwlink/?linkid=849601#definition-version

**Comment by eredrolo** [comment]
@jely2002 It is **1.343.1390.0**
  
![Screenshot 2021-07-21 195749](https://user-images.githubusercontent.com/74611933/126506169-cc4acd86-440c-47e3-b3d3-e08fc90a4269.png)

Looks like there was an update today and they fixed it. It's not flagging the portable version now and it's working fine.

**Comment by jely2002** [comment]
Good to know they fixed it. Closing the issue.
