### ISSUE TITLE
Modify Download Rate

### ISSUE THREAD

**Issue by Pocire** [jely2002/youtube-dl-gui#140]
**Is your feature request related to a problem? Please describe.**
No, i would like to download at the rate i want, because i don't currently have fiber.

**Describe the solution you'd like**
Either the ability to choose the rate or to put my own rate.

**Additional context**
Limit rate for all videos not just one video, i mean this option as a general setting that could possibly be modified while downloading too. Thank you for considering this :)
![Rate limit github jely2002](https://user-images.githubusercontent.com/25608815/126880993-bc8d65b8-9f0f-4979-b5a2-672fd8029ac6.JPG)

**Comment by jely2002** [comment]
Hi, thank you for the feature request.

For the time being I can only add a rate limit setting per video. That also can't be changed while the video is downloading.
In the future I might switch over to using an external downloader such as aria2c, which has support for the features you requested.
For now I will add a bandwith limit per video.

If you have any more questions feel free to ask.

**Comment by Pocire** [comment]
Okay, seems fine to me, thank you for your quick answer!

Have a good day!

**Comment by jely2002** [comment]
I have added this feature. Under the 'network' section in settings there is now a rate-limit option. This feature will release on the next feature update.

This is how it will look:
![image](https://user-images.githubusercontent.com/20154900/126881440-6105a8fd-c6b7-44eb-81f6-f95dc9e69652.png)
