### ISSUE TITLE
save download setting

### ISSUE THREAD

**Issue by Pesoen** [jely2002/youtube-dl-gui#141]
**Is your feature request related to a problem? Please describe.**
i kinda hate that i have to remember to switch it from video+audio to only audio everytime i close the program.

**Describe the solution you'd like**
save when i switch from video+audio to audio, so i dont have to keep switching it first thing when i start the program.

**Describe alternatives you've considered**
a setting if you want video at all, or switching program to something else.

**Additional context**
not much, seems simple enough, and should not take more than a few minutes to implement since it already stores the download location correctly.

**Comment by jely2002** [comment]
This feature has been implemented, it will release in upcoming update 2.3.0.
