### ISSUE TITLE
Globally listens to Ctrl + Shift + V shortcut

### ISSUE THREAD

**Issue by Aankhen** [jely2002/youtube-dl-gui#144]
**Describe the bug**
The shortcut <kbd><kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>V</kbd></kbd> in any application prevents the normal behaviour and pastes the clipboard contents into youtube-dl-gui.

**To Reproduce**
1. Open youtube-dl-gui
2. Switch focus to another window and copy something.
3. Press <kbd><kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>V</kbd></kbd>.

**Expected behavior**
Nothing in youtube-dl-gui.

**Additional info (please complete the following information):**
 - OS: Windows 10
 - Application version: 2.2.2

**Comment by jely2002** [comment]
Hi Aankhen,

This is in fact a feature, see #101. I will add a setting so this feature can be disabled.

If you have any questions, feel free to ask.

**Comment by Aankhen** [comment]
I understand. A setting would be great! Thanks a lot.

**Comment by WilliamIsted** [comment]
Thanks for adding the preference, very much appreciated. I just had to hunt down what was taking priority over Sublimes duplicate line shortcut which brought me here.
