### ISSUE TITLE
Video downloading occasionally slows to a crawl and never recovers

### ISSUE THREAD

**Issue by coderbot16** [jely2002/youtube-dl-gui#147]
**Describe the bug**
While downloading videos from YouTube, occasionally a video download will start off very slow and never recover. On my internet connection which is capable of speeds around 12MB/s, download speed will slow down to the order of kilobytes per second. Cancelling and restarting the download appears to fix the issue.

This affects all downloads from YouTube. However, when downloading large playlists, it's not possible to restart a download without completely restarting the playlist download, which involves downloading video metadata for the entire playlist and checking every video up to that point. It's entirely possible that during the process of getting restarted, the downloads will slow back down again. As a result, as playlist size increases, the number of attempts (and time) required to fully download the playlist rises to infinity.

One way to work around this is manually pasting in each video of the playlist, which allows you to restart individual downloads as needed. Unfortunately, this is very inconvenient.

**To Reproduce**
1. Set the "Max Concurrent Jobs" option to `1`. This happens at any size, but with fewer jobs, the freeze happens quicker since progress only stalls when all threads are stuck on a stalled job.
2. Download a large playlist.
2. Watch the download progress & file sizes of downloaded files.
3. Eventually things slow down to a crawl. In-progress files only increase in size by a few kilobytes each minute, and after waiting for hours no significant progress has been made.

**Expected behavior**
Obviously I'd expect for downloads to not stall at all. However, that might be unavoidable with weirdness of YouTube. If possible, it would be nice if this tool could detect when a download has frozen and automatically restart it with some delay. In addition, it would be nice to see the progress of individual video downloads.

**Screenshots**
Not really applicable.

**Additional info (please complete the following information):**
 - OS: Windows 10 x64
 - Application version: 2.2.2
 - Application type: Portable

**Additional context**

**Comment by jely2002** [comment]
Hi coderbot,

I'm aware of the issue and was able to replicate it. It is however really hard for me to fix. Youtube-dl has to find a fix for this, it has to do with YouTube throttling youtube-dl on purpose. I can of course retry the video automatically, but what if someone really has an internet speed that is so slow? Then their video will keep on restarting. So this is not a possibility.

For more info on the issue:
https://github.com/ytdl-org/youtube-dl/issues/29326#issuecomment-865985377

A little tip, in the settings of this app, all the way at the bottom. You can select when to split a playlist into separate videos, you can increase that amount. So you can cancel/retry individual videos and see their progress.

If you have any other questions, feel free to ask.

**Comment by thaynos** [comment]
> Hi coderbot,
> 
> but what if someone really has an internet speed that is so slow? Then their video will keep on restarting. So this is not a possibility.

well you could make a wifi speed test run in the background or ask the user to input it themselves

**Comment by thaynos** [comment]
also in the link you sent there seem to be solutions, can you try to implement that in the app? i cant make a fork myself cuz im too inexperienced :(

**Comment by jely2002** [comment]
Running a wifi speed test in the background is not okay. This will consume quite some bandwidth that the user pays for / needs.
Adding this is also a lot of work for a small workaround, for something that might get fixed. 

There are solutions, they just haven't been implemented, as this requires youtube-dl to have a functioning javascript interpreter. This is not something I can just add to this app, it needs to be added to youtube-dl.

 The other solution posted in the thread is one from youtube-dlp, this is also not a solution, just a temporary workaround that restarts the video if the speed drops below a certain amount. Which is as I explained in the previous comment not a good solution.

The best thing to do here is to just wait for a fix. There isn't really a way of fixing this from my end.
