### ISSUE TITLE
add youtube dlp

### ISSUE THREAD

**Issue by i8cczshd** [jely2002/youtube-dl-gui#151]
can we get [youtube dlp](https://github.com/yt-dlp/yt-dlp) as an option? looks like youtube dl is dead

**Comment by SilverRoll** [comment]
You can just disable auto-update and drop yt-dlp.exe into C:\Users\username\AppData\Local\Programs\youtube-dl-gui\resources\app.asar.unpacked\binaries\. It needs to be renamed to youtube-dl.exe.

**Comment by jely2002** [comment]
Will look into adding youtube-dlp, as it has some nice features, and is not dead.
With auto-update of course.

**Comment by jely2002** [comment]
yt-dlp has been added with auto-updating starting from version 2.4.0.

**Comment by Silver-Volt4** [comment]
pog!

**Comment by magsnetcud** [comment]
thank you so much!!!

**Comment by Mitezuss** [comment]
yt-dlp.exe is not working, with youtube (right now)

but yt-dl.exe is working

So, can add a option to select what .EXE to use to manage the downloads ?

**Comment by eladkarako** [comment]
there are quirks you need to fix by adding some additional switches though,  
for example mkv would have webp thumbnail which isn't supported in pretty much anywhere, and this is the default for some reason. so if you use `--embed-thumbnail` you have to also add `--convert-thumbnails jpg`.

and you can make it skip through errors and still provide some results with a combination of `--no-abort-on-error` and `--skip-unavailable-fragments`.
