### ISSUE TITLE
2.3.0 portable requires ffmpeg 

### ISSUE THREAD

**Issue by Antiever** [jely2002/youtube-dl-gui#153]
`YouTube-Downloader-GUI-2.2.2-portable.exe`  works just fine.

With `Open-Video-Downloader-2.3.0-portable.exe `
![Open_Video_Downloader_2021-08-19_07-42-50](https://user-images.githubusercontent.com/9666515/130009485-eff8a92d-ff75-47eb-b8b1-3798f938e8be.png)

OS Win7 x64

**Comment by vitacell** [comment]
I have "Error! ffmpeg not found.", it's outputs right when audio and video ready for merge.
Version 2.3.0 appimage, tested on Slackware64-14.2 and Mint20.2. (Both with fully working ffmpeg).

**Comment by jely2002** [comment]
I'm aware of the issue. My app always uses the shipped ffmpeg, so having it installed won't help in this case. For now I advice to fall back to v2.2.2 while I fix this.

**Comment by jely2002** [comment]
When you run the 2.3.0 portable is there a folder being created next to the executable, called: `open-video-downloader`?
If yes, are you able to send me a list of what's in that folder?

**Comment by Antiever** [comment]
> a list of what's in that folder?

```
.
|   Open-Video-Downloader-2.3.0-portable.exe
|
\---open-video-downloader
        taskList
        userSettings
        youtube-dl.exe
        ytdlVersion
```

**Comment by vitacell** [comment]
> A temporary fix would be to download ffmpeg.exe from this repo, and put it in that folder. That would fix the error for now.

And for AppImage?

**Comment by jely2002** [comment]
This should now be fixed. The portable version and appImage version of 2.3.0 are replaced with working versions.
