### ISSUE TITLE
Offering to help with translating the project

### ISSUE THREAD

**Issue by sanmacorz** [jely2002/youtube-dl-gui#154]
I'm willing to help translate the app to Spanish, I have been using the program for quite a long time now, and I have recommended it to friends or family that don't quite understand English so I have to keep explaining them every option.

Are there any plans on making a translation campaign? I mean, there are websites like Crowdin which support open source software, but they are not quite free software supporters, but I'm sure you could use some alternative out there. And I think a part of the community for this project would be glad to help, including me of course.

I mean if the owner of the project doesn't have any plans for this, I don't mind too much, it's just an idea for a request :smiley:

**Comment by NebelNidas** [comment]
I would be happy to provide a German translation, if needed! ☺

**Comment by jely2002** [comment]
I will start looking into a good way to add localization to the project. Stay tuned!

**Comment by Kernel-chan** [comment]
Please do, I would love to help in Spanish as well.

**Comment by ZeinabBahaa** [comment]
I would also like to help translate into Arabic and French
