### ISSUE TITLE
"uncaught exception" when downloading a file twice with the same title

### ISSUE THREAD

**Issue by EricE549X** [jely2002/youtube-dl-gui#155]
**Describe the bug**
when i download a video file once, it works as expected. but when i download the same file again with the same file name, this pops up
<img width="372" alt="Screen Shot 2021-08-21 at 8 42 24 AM" src="https://user-images.githubusercontent.com/86898409/130322288-19f66fff-aa38-45e4-8d97-dfbaf34a2966.png">

**To Reproduce**
1. copy + paste a link
2. download the video
3. don't rename the file
4. repeat steps 1 and 2
5. see error

**Expected behavior**
when i download the video again, it should know to replace the file rather than get caught in an error.

**Additional info (please complete the following information):**
 - OS: macOS 11.5.2
 - Application version: 2.3.0
 - Application type: macOS version from .dmg

**Comment by jely2002** [comment]
Thanks for the report!
It has been fixed now, and will be released in the next bugfix update.
