### ISSUE TITLE
2.3.0 Portable Various Errors - Missing Stuff, python, ffmpeg, youtube-dl

### ISSUE THREAD

**Issue by starfishpatkhoo** [jely2002/youtube-dl-gui#156]
Running 2.3.0 portable results in various errors related with missing components. Rolling back to 2.2.0 portable resolves the error.

- Windows 10 x64
- Open Video Downloader 2.3.0 Portable

![20210822-084421 371 screenshot](https://user-images.githubusercontent.com/46368879/130338384-16832e93-d4a8-482d-a554-229fa3b45c45.png)

**Comment by starfishpatkhoo** [comment]
Oops, maybe the same bug as #153

**Comment by vitacell** [comment]
I have "Error! ffmpeg not found.", it's outputs right when audio and video ready for merge.
Version 2.3.0 appimage, tested on Slackware64-14.2 and Mint20.2.

**Comment by jely2002** [comment]
This should now be fixed. The portable version and appImage version of 2.3.0 are replaced with working versions.

**Comment by sevar83** [comment]
Just downloaded the portable 2.3.0 and I have the same error for missing Python.

**Comment by jely2002** [comment]
Thanks for reporting, I have deployed a fix for this, this was a separate issue. I have replaced the 2.3.0 portable executable.
Make sure to remove the open-video-downloader folder, before trying the new version.
