### ISSUE TITLE
youtube-dl-gui portable

### ISSUE THREAD

**Issue by candrapersada** [jely2002/youtube-dl-gui#16]
add youtube-dl-gui portable for windows.

**Comment by jely2002** [comment]
Hi candrapersada,
I will take a look into this as i can image how a portable version can be handy. I will post another comment as soon as i have added a portable version to the last release.

**Comment by jely2002** [comment]
I have added a portable version to release 1.8.4, future releases will now include a portable version as standard.
Closing the issue.

**Comment by candrapersada** [comment]
how to update for youtube-dl-gui portabel?

**Comment by jely2002** [comment]
The portable version does not auto-update, you can just download the new portable version from the latest release and use that one.
