### ISSUE TITLE
Show file in folder/Open file failing to function with some default generated filenames.

### ISSUE THREAD

**Issue by tallos** [jely2002/youtube-dl-gui#160]
**Describe the bug**
downloaded videos with titles that contain some emoji/missing fonts can cause the Show File in Folder and Open file buttons to fail in 2.3.0 if windows cannot properly display the emoji and replaces them with the missing font box. an example of one of the emoji: 🌿
These functioned correctly in 2.2.1 Portable even if windows could not display the emoji or font(ie replaced it with the missing font box)

**To Reproduce**
1. download the following video with 2.3.0 Portable using default Title or Title+quality filename: https://www.youtube.com/watch?v=le9AAt8B5Gc
2. Click Show File in Folder
3. Nothing will happen
4. Click Open file
5. See Windows cannot find path error, the filepath shown will not have either the emoji or the missing font box icon.

**Expected behavior**
Show file location should open the folder the file was saved in, Open file should open the file.

**Additional info (please complete the following information):**
2.3.0 Portable
![fail to find file](https://user-images.githubusercontent.com/3512963/131200661-37f37120-bb52-4d21-9b93-fd1ab8d6433a.JPG)

**Additional context**
I tested this in both 2.3.0Portable and 2.2.1Portable, 2.2.1 correctly was able to open both the file and the file location, 2.3.0 failed both. Both successfully download the file.

**Comment by jely2002** [comment]
This happens because in 2.3.0 I get the filename from the console, which is much more reliable in many cases. What I didn't know is that apparently emoji's don't get passed into the console.

I'll see if I can fix this by using the old method when the file doesn't exist with the new method.

**Comment by jely2002** [comment]
This should now be fixed. The video you mentioned will open fine. This fix will be released on the next bugfix update.
