### ISSUE TITLE
Add automatic metadata JSON download

### ISSUE THREAD

**Issue by kajatak** [jely2002/youtube-dl-gui#164]
**Is your feature request related to a problem? Please describe.**
QOL improvement, no issues per se.

Currently it's possible to download the metadata automatically and include that in the video file, but downloading the comprehensive metadata in JSON format takes extra clicks which becomes a chore easily.

**Describe the solution you'd like**
Add extra option to automatically download metadata in JSON format. Maybe switch the current "Save metadata" checkbox to a dropdown menu with "Save medatada (to video)" and "Save metadata (to video and) as JSON" as options.

**Comment by Hannah-GBS** [comment]
Where did this go?

**Comment by jely2002** [comment]
This was one of the features that were dropped during the v3 development. If there's still use-cases for this then I'll re-open this and once again implement it.

**Comment by Hannah-GBS** [comment]
I personally used the JSON file to generate custom NFO files for use with the Plex XBMC agent. Not sure if there is a wide desire for it though

**Comment by Robubble** [comment]
Yeah, I'd find the option for a separate json also better for that use-case
