### ISSUE TITLE
HELP | Custom video name

### ISSUE THREAD

**Issue by Warden20** [jely2002/youtube-dl-gui#167]
Please help me, I want to be able to have a personal name when downloading videos, but I don't know how.
 I would like it to be like this: 2021-08-31 (date )|Video name | Youtube channel | video url
Thank you very much in advance

**Comment by jely2002** [comment]
Hi Warden20!

If you go to settings -> Output -> Filename format, you can set it to Custom and define your own format.
The `|` character is not allowed in filenames, the same is for some characters in a URL.

The closest I got to what you want is this:

upload date-title-channel-video id.mp4

You can set this by entering the following in the text box beneath the custom selector:
`%(upload_date)s-%(title).100s-%(channel)s-%(id)s.%(ext)s`

Hope I helped. Let me know If you have any other questions
