### ISSUE TITLE
2.3.0 AppImage: bundled ffmpeg not working

### ISSUE THREAD

**Issue by db47h** [jely2002/youtube-dl-gui#169]
With the 2.3.0 AppImage, audio only downloads are not converted. This seems to be an issue with the bundled ffmpeg executable that has been renamed to `ffmpeg-linux` instead of just `ffmpeg`.

Excerpt from the logs:

```
WARNING: Cannot identify executable /home/db47h/.youtube-dl-gui/ffmpeg-linux, its basename should be one of avprobe, avconv, ffmpeg, ffprobe. Continuing without avconv/ffmpeg.
WARNING: O4irXQhgMqg: writing DASH m4a. Only some players support this container. Install ffmpeg or avconv to fix this automatically.
ERROR: ffprobe/avprobe and ffmpeg/avconv not found. Please install one.
```

This worked fine in 2.2.2

**Comment by jely2002** [comment]
Thanks for the report. Apparently youtube-dl on linux/macos needs the ffmpeg file to be called ffmpeg. I have reverted the rename. A fixed version will release with version 2.3.1. 

If it still doesn't work on v2.3.1 try removing the `.youtube-dl-gui` directory from your home directory.
