### ISSUE TITLE
When showing video quality show some description to it as YouTube does.

### ISSUE THREAD

**Issue by clicky6** [jely2002/youtube-dl-gui#177]
When showing qualities like 1080p & 2160p show a small size text over them where HD,4K etc. is written.
![4](https://user-images.githubusercontent.com/89839714/132089170-8e04891b-ab3c-4848-a383-946355856958.png)

**Comment by jely2002** [comment]
I will not be adding this. As it doesn't provide much more in the way of usability. And it clashes with the style of the app.

**Comment by clicky6** [comment]
No issues, It was just a suggestion.
