### ISSUE TITLE
Make the settings menu more intuitive.

### ISSUE THREAD

**Issue by clicky6** [jely2002/youtube-dl-gui#178]
PRESENT DAY settings menu in youtube-dl-gui is not good it should be like showing all topics in left side and settings on the right side.

PRESENT DAY SETTINGS MENU.
![5](https://user-images.githubusercontent.com/89839714/132089556-f939dcd0-1c8b-40ab-9a42-60457aac2240.png)

IT SHOULD BE LIKE.
![6](https://user-images.githubusercontent.com/89839714/132089561-35b9ec68-13b2-4ed8-8a27-7b1242431c56.png)

This example is just to demonstrate that how the settings menu should look like.

It helps very much so that we can find specific settings and doesn't make settings look like a mess.

And it would be also great to have a search bar in settings so we can find specific settings that we want. [OPTIONAL]

**Comment by EricE549X** [comment]
as the people in the genius forums say, i co-sign this
