### ISSUE TITLE
worst for video and audio

### ISSUE THREAD

**Issue by candrapersada** [jely2002/youtube-dl-gui#18]
how to use worstvideo and worstaudio?
![aa](https://user-images.githubusercontent.com/36833664/99283680-eabe1380-2867-11eb-97ff-40bb6e4d2f6a.PNG)

**Comment by jely2002** [comment]
Great catch,  that is currently not an option. I do believe it should be an option, so I think I will be adding this to update 1.8.5.
I will be adding an extra box next to the resolution, where you will be able to select the audio quality.

**Comment by candrapersada** [comment]
add worstvideo and worstaudio

**Comment by jely2002** [comment]
I just stated that will be adding this in update 1.8.5. Locking comments for now.
