### ISSUE TITLE
Arrange videos in folders 

### ISSUE THREAD

**Issue by ZeinabBahaa** [jely2002/youtube-dl-gui#180]
hi
When I download an entire channel or playlist, all videos are saved randomly
It would be nice if each playlist was saved in its own folder with the name of the downloaded playlist 
thanks

**Comment by NebelNidas** [comment]
An option for that would be nice, yeah

**Comment by mj0123456789** [comment]
Hello @jely2002 ,
What would be the syntax for doing so using the youtube channel name please? (maybe a documentation I did not see)
Cheers

**Comment by jely2002** [comment]
Hi @mj0123456789,

You can use this to put it in a folder with the channel name.
`%(channel)/%(title)s.%(ext)s`

Or this if you want to use the ID:
`%(channel_id)/%(title)s.%(ext)s`

For more info on this see the youtube-dl documentation.
https://github.com/ytdl-org/youtube-dl#output-template

**Comment by mj0123456789** [comment]
Thanks a lot!
Your tool is wonderful, thx.

**Comment by mj0123456789** [comment]
PS : correct syntax in my case:
%(channel)s/%(title)s.%(ext)s
not to get an error ("/" not allowed)
Regards
