### ISSUE TITLE
For videos above 1440p resolution, only audio is downloaded?

### ISSUE THREAD

**Issue by MeowRay** [jely2002/youtube-dl-gui#182]
![image](https://user-images.githubusercontent.com/29674595/132128351-36256907-67b5-4b2f-9004-3fe37d108da5.png)

**Comment by jely2002** [comment]
Hi MeowRay,

That shouldn't be happening! 
When I try downloading this video: https://www.youtube.com/watch?v=bON-KPiiNCk
Everything seems to work fine, could you give me a little bit more info?
Like:
- What URL did you try to download?
- What version of the app are you using?

**Comment by MeowRay** [comment]
> Hi MeowRay,
> 
> That shouldn't be happening!
> When I try downloading this video: https://www.youtube.com/watch?v=bON-KPiiNCk
> Everything seems to work fine, could you give me a little bit more info?
> Like:
> 
> * What URL did you try to download?
> * What version of the app are you using?

https://www.youtube.com/watch?v=PB4gId2mPNc
Choose 8k resolution to download
It seems that only some videos have this problem

**Comment by jely2002** [comment]
Looks like that video only has the av1 encoding available. Make sure your video player supports this format!
![image](https://user-images.githubusercontent.com/20154900/132135013-27211e11-d157-4d3c-b231-acd143d939ed.png)


I am able to open it in VLC media player and Windows movies & tv (after installing the AV1 codec pack).

You can enable codec selection in the app settings (all the way at the bottom), that way you can choose what encoding you want, and choose another one than AV1 when possible.

Closing this, let me know if you still have any questions.
