### ISSUE TITLE
sponsorblock

### ISSUE THREAD

**Issue by TheAlphaReturns** [jely2002/youtube-dl-gui#183]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when Sponsors

**Describe the solution you'd like**
no sponsors

**Describe alternatives you've considered**
sponskrub but takes so much extra work

**Comment by NebelNidas** [comment]
This would depend on #151, as only `youtube-dlp` has a SponsorBlock integration: https://github.com/yt-dlp/yt-dlp#sponsorblock-options

**Comment by jely2002** [comment]
Sponsorblock is super cool, will definitely be looking at it when I implement youtube-dlp.

**Comment by jely2002** [comment]
Version 2.4.0 of the app uses yt-dlp. This means sponsorblock support is there as well. In settings there is now a new section where you can select what parts of videos should get blocked or flagged.

**Comment by wierdopi** [comment]
damn, well with yt-dlp and sponsorblock this is now by *far* the best yt downloader. foss ftw
