### ISSUE TITLE
Soundcloud fetches metadata then vanish

### ISSUE THREAD

**Issue by lukasong** [jely2002/youtube-dl-gui#184]
**Describe the bug**
Soundcloud downloads start to fetch metadata an then just vanish.

**Additional info (please complete the following information):**
 - Latest OSX and latest Youtube-DL-GUI, alongside Youtube-DL set to auto-update in GUI preferences

**Comment by jely2002** [comment]
Thanks for the report, I was able to reproduce the issue. And it has now been fixed, the fix will roll out with the next update.
