### ISSUE TITLE
Allow saving of queue list

### ISSUE THREAD

**Issue by gitraghuram** [jely2002/youtube-dl-gui#188]
Currently after closing the ui, the queue list is forgotten. User has to reach/copy the individual urls of playlists, from somewhere else.
Instead allow user to easily get back to those playlist urls from this UI itself. Save also the directories to where the individual playlists were downloaded.
For example, keep history of the urls and related directories, and let user choose one or more from that list again to add to queue.
This would help to download new videos from old playlists.

Another way is to let user do a request to search based on saved playlists for any newer videos, and suggest to user to allow download of them.

**Comment by jely2002** [comment]
Hi! This is already a future, if you still have videos in your queue. The app will ask on the next start if you want to restore them.
![image](https://user-images.githubusercontent.com/20154900/133621314-8c88b2ac-117d-443e-b4b7-d83159b83d63.png)

Let me know if you happen to have any more questions.

**Comment by gitraghuram** [comment]
I do not see such message about restoring.
Here are the steps I am referring to.
1. In the text box of "Enter URLs below", enter a link to a PLAY LIST.
For example:   paste the url:   https://www.youtube.com/watch?list=PLAPrVB8wngPnSeclgc10Y1zKTePXOEKHQ
which is one for a play list.
2. Click Add. That url would now appear in the Download list. 
3. Click on the Download icon button. It would start downloading. (But this step should not be necessary for the purpose of this enhancement request).
4. Close the software and confirm close.
5. Now open the software.
6. It would be nice if the url copied above is accessible within the software. Currently it is empty.
7. In addition, even after it downloads all the existing videos within a playlist, the playlist should be still available later within the software, and we should be able to check and download any new videos added to that playlist, into the directory we had specified originally.
8. Allow for multiple such playlists to be saved for this purpose within the software.
