### ISSUE TITLE
Building on 32bit system bundles in 64bit ffmpeg

### ISSUE THREAD

**Issue by samlinz** [jely2002/youtube-dl-gui#189]
**Describe the bug**

When building youtube-dl-gui on 32bit system, Raspberry Pi OS in my case, the build process bundles in 64bit executable of ffmpeg, which causes video-audio merging and other processes after download to fail with message "ffmpeg not found".

The executable is in ~/.youtube-dl-gui/ffmpeg

I verified that the executable is 64bit by running "od -t x1 -t c foo | head -n 2" and verifying that the fifth byte is "2" for 64bit process.

Ad hoc fix by creating symbolic link with "ln -s $(which ffmpeg) ~/.youtube-dl-gui/ffmpeg". After this everything works as it should on Raspberry Pi OS.

**To Reproduce**
1. Clone GitHub repo on a 32bit system, like Raspberry Pi OS
2. Run build steps described in GitHub README i.e. "npm install" and "npx electron-builder --linux --armv7l" with the addition of architecture for 32bit build
3. Run the program from dist/
4. Download any video that requires ffmpeg post-processing, like merging video and audio files

**Expected behavior**
The download and post-processing steps would succeed without errors

**Screenshots**

**Additional info (please complete the following information):**
 - OS: Raspberry Pi OS "Linux raspberrypi 5.10.52-v7l+ #1441 SMP Tue Aug 3 18:11:56 BST 2021 armv7l GNU/Linux"
 - Application version v2.3.1
 - Application type self-built

**Additional context**

**Comment by jely2002** [comment]
As stated in the README builds on platforms that I don't build are not supported.

If you want to build for 32 bit you'll have to swap the ffmpeg.exe in /binaries with a 32bit executable. This way it will of course bundle the right executable. Not sure if you will run into other issues.
