### ISSUE TITLE
Why does my download stop before it is finished?

### ISSUE THREAD

**Issue by candrapersada** [jely2002/youtube-dl-gui#19]
add feature restart download, if stuck. auto resume.

**Comment by jely2002** [comment]
You can restart the download by yourself by just pasting the link in again. The download will start where it left off since ytdl stores partially downloaded data in a .part file.
I would like to keep this application and its UI simple, besides I do not really see that much of a use for a restart button. So I'm afraid this will not be implemented.

**Comment by candrapersada** [comment]
what I mean is the feature to automatically resume downloads when the download crashes without clicking the restart button

**Comment by jely2002** [comment]
Could you provide me with an example of a download that crashes? I have never seen this behavior before. 
Also there isn't really a way to detect a crashed download and resume it, so again I will most likely not be implementing this.

**Comment by candrapersada** [comment]
youtube-dl stops downloading something, before it is finished.

**Comment by jely2002** [comment]
I have never had youtube-dl stop downloadng something before it is finshed. If you cannot provide a reproducable example I will lock this issue.

**Comment by candrapersada** [comment]
`ERROR: unable to download video data: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>`

**Comment by jely2002** [comment]
This error message indicates a problem with a proxy/vpn or just a bad connection in general. This has nothing to do with my GUI but more with youtube-dl itself and or your connection.
