### ISSUE TITLE
How do I make it ignore my default youtube-dl.conf file?

### ISSUE THREAD

**Issue by IA21** [jely2002/youtube-dl-gui#190]
**Describe the bug**
I have my own copy of youtube-dl in my user folder and a youtube-dl.conf file along with that. There's some default settings I have in there (like always download audio only). I have downloaded the portable version of this software and I have set it to download both video+audio from the gui dropdowns. But it keeps downloading audio only files. I updated my own youtube-dl.conf file and removed the audio only lines and of course this software now works properly.

Since it comes with its own copy of youtube-dl, it should not make any use of my own youtube-dl.exe or its youtube-dl.conf file. Thinking that, I created a separate youtube-dl.conf file in the portable directory (alongside the youtube-dl that came with it) and it keeps ignoring it and keep using my own youtube-dl.conf file from the user directory.

**To Reproduce**
1. place a youtube-dl.conf file in the user directory and add that to path variable.
2. run open video downloader and watch it ignore its own settings and use the settings from conf file in the path file.

**Expected behavior**
I'm using the portable version. It has its own youtube-dl. It should also pay attention to its own youtube-dl.conf file. It should not be using files from path as highest priority.

**Screenshots**
none

**Additional info (please complete the following information):**
 - OS: Windows 10 (x64)
 - Application version: 2.3.1
 - Application type: portable

**Additional context**
none

**Comment by jely2002** [comment]
Thanks for the report, I will add the `--ignore-config` parameter to all downloads. So it will ignore any configs the user has,

**Comment by jely2002** [comment]
The app will now always ignore any configs the user has. This will release in the next update.
