### ISSUE TITLE
can't download any video on my windows 10

### ISSUE THREAD

**Issue by ihavestartup** [jely2002/youtube-dl-gui#196]
i can't download any video or playlist, when i put the link its always error.

in version 2.3.1

![image](https://user-images.githubusercontent.com/78952756/133327063-1702c626-ca82-4a6d-b6f8-70dcf4f489bb.png)

**Comment by jely2002** [comment]
Thanks for the report, could you click on 'Show full error' and send me what it says?
Also what version of the app are you using?

**Comment by huhahuhahuha** [comment]
![image](https://user-images.githubusercontent.com/41940279/133868462-2e30193a-30b9-46a9-8289-23e258085806.png)

**Comment by superswan** [comment]
I can't recreate issue but I suggest running as admin and disabling any Anti-Malware services.

**Comment by jely2002** [comment]
I'm also unable to replicate this issue. This error is most likely some program interfering with the youtube-dl.exe file, this could be anti-virus/malware or any other program that opens/scans this file. Will be closing this issue, as this is not an open video downloader related bug.
