### ISSUE TITLE
direct download m3u8

### ISSUE THREAD

**Issue by clintwan** [jely2002/youtube-dl-gui#197]
if i run
```
./youtube-dl 'https://99sex.xyz/video/m3u8/93c14a975ea94ffe12990c60236ab60030bc2fd5.m3u8?&video_server=direct_hosts2'
```

yd will download sources in that m3u8 and merge to a mp4 file finally (ffmpeg in path).

if youtube-dl-gui support m3u8 ( just keep yd's feature) will be great.

**Comment by jely2002** [comment]
The example video you provided will now download fine on 2.4.0. The progress bar does seem to not always work, but it will download it. Progress can be followed in the log.
