### ISSUE TITLE
add youtube-dlc

### ISSUE THREAD

**Issue by candrapersada** [jely2002/youtube-dl-gui#20]
Youtube-dl has been heavily [uncommitted for the past few month](https://github.com/ytdl-org/youtube-dl/graphs/commit-activity)s, and there's been a [new fork](https://github.com/blackjack4494/yt-dlc/releases) that's kind-of taken on the reigns. Wondering if it would be possible to perhaps give the option of supporting that instead of the original one?

**Comment by jely2002** [comment]
YouTube-DL has just gone back online, and has had 2 updates in 1 night. I would not call that uncommited. 
As long as youtube-dl provides all the necessary features for this GUI I will keep using it.
