### ISSUE TITLE
No videos from CDA in queue 

### ISSUE THREAD

**Issue by babygappa** [jely2002/youtube-dl-gui#212]
Hi,
I wanted to download some film from CDA, a website that is listed as a supported site, but whenever I try to add it to the queue the app tries to download the metadata and the item just disappears. Nothing else happens. There is no error showing
Since CDA is listed as one of the supported websites I expected the app to download the videos with no problem.

![01](https://user-images.githubusercontent.com/92026358/136190150-1bdb9f2b-ce6a-4b22-be62-f0baf8e82fe6.JPG)
![02](https://user-images.githubusercontent.com/92026358/136190151-5d978a15-7a1b-4198-bd46-3af31da7134e.JPG)
.

 - OS: WIndows 10 Home
 - Application version: 2.3.1
 - Application type: Microsoft Store

Looking forward to your help.

**Comment by jely2002** [comment]
This appears to be fixed by switching to yt-dlp. Progress on this switch can be tracked in #151.
It will be releasing soon though.

**Comment by jely2002** [comment]
The video link you provided works fine in 2.4.0, after switching to youtube-dlp.
