### ISSUE TITLE
Download from a channel

### ISSUE THREAD

**Issue by syedmahm** [jely2002/youtube-dl-gui#22]
**Is your feature request related to a problem? Please describe.**
- No problem. Just a feature request.
**Describe the solution you'd like**
**- I would like to have a download option from a channel. Currently it recognizes a playlist, but not a channel. And also, please add the option to select video numbers for the channel like now you have for the playlist.**
**Describe alternatives you've considered**
- N/A
**Additional context**
- N/A

**Comment by jely2002** [comment]
Hi syedmahm,
Great idea! I will be adding this in version 1.8.6.

**Comment by syedmahm** [comment]
Thank you! Will my app be auto updated once you release the update? I use the MacOS version.

    On Saturday, November 21, 2020, 3:08:36 PM MST, Jelle Glebbeek <notifications@github.com> wrote:  
 
 


Hi syedmahm,
Great idea! I will be adding this in version 1.8.6.

**Comment by jely2002** [comment]
Your app will not be auto-updated on MacOS. This is because MacOS requires code signing for auto-updating. Code signing requires a certificate from apple which I cannot afford. You will however be notified with a little popup if a new version is available, so you may download it from GitHub.

**Comment by jely2002** [comment]
This feature has been added in 1.8.6! Closing the issue.

**Comment by syedmahm** [comment]
Thank you.
