### ISSUE TITLE
this video can't download

### ISSUE THREAD

**Issue by sojey** [jely2002/youtube-dl-gui#222]
https://www.youtube.com/watch?v=TvHsN5-YBLI

software can parse this URL address, but I have tried it for multiple periods of time, but I can’t download it. 

Error reported! Report ID: a4e622af

please find bug and fix it. thx.

**Comment by jely2002** [comment]
Thanks for reporting the error. It works fine for me. Due to the high amount of error reports I'm getting, sadly it looks like yours didn't come through. If it happens again, let me know what the error message was.

I'll be closing this issue for now.
