### ISSUE TITLE
Limited download speed?

### ISSUE THREAD

**Issue by Nebbytales** [jely2002/youtube-dl-gui#225]
Hi,

For some reason, I'm only getting 58kbps download speed through Open Video Downloader even though multiple applications are closed and I'm getting 285mbps through speedtest. I've updated the client and i'm still facing the same issue.

Thanks.

**Comment by Airey001** [comment]
I am seeing this too videos that are just minutes long i am getting speeds around 50 to 60  KiB's with downloads times in the 1 to 2 hour range.  If i use an extension in chrome to download the same videos it takes seconds.

**Comment by areasu** [comment]
Same issue here. I have a 500mbits connection and every download is fast expect in this app its around 40-70kbs. Very very slow.

**Comment by jely2002** [comment]
This has to do with YouTube throttling all youtube-dl downloads. When I have some free time on my hands I'll start working on moving over to youtube-dlp, which will hopefully solve the issue.

More details about the issue can be found here https://github.com/ytdl-org/youtube-dl/issues/29326.

**Comment by EricE549X** [comment]
> Meanwhile, I had success by just overwriting the ytdl exe in `%appdata%/youtube-dl-gui(-portable)/youtube-dl.exe` with the [yt-dlp executable](https://github.com/yt-dlp/yt-dlp/releases).
> 
> The throttling seems to be tied to how far you've watched a video on the actual website too. I got throttled at 70% of a download because I had watched a video up until that point and not continued, but as soon as I resumed in my browser it would download the rest of the way...

does anyone know how to do this for mac?

**Comment by jely2002** [comment]
You could show the package contents of open-video-downloader.app and swap out the youtube-dl executable. 
I think this would work, but not sure as I don't own a mac.

**Comment by jely2002** [comment]
This is now solved in version 2.4.0, this version uses yt-dlp.
