### ISSUE TITLE
Specify download quality as default

### ISSUE THREAD

**Issue by drd2aiki** [jely2002/youtube-dl-gui#226]
Is there a way to only download videos at a certain quality level? Let's say 480p or 720p, even though lower and higher options are available? I can do this with the drop-down per video, but a default setting would be great!

Thanks!

**Comment by jely2002** [comment]
Hi! At the bottom of the screen is a setting with 'Best' selected as default. Using this dropdown you can set the quality of all videos currently in the queue.

This is how it could look like for example:
The qualities that are available depend on which videos you have added to the queue.
![image](https://user-images.githubusercontent.com/20154900/141655569-4d259371-5389-4907-9736-12729e80a9de.png)
