### ISSUE TITLE
Very slow downloading

### ISSUE THREAD

**Issue by ghost** [jely2002/youtube-dl-gui#228]
**Describe the bug**
Video Downloading is very slow, never happened before. 

**To Reproduce**
1. Open Open Video downloader
2. Paste any video link
3. Click Download
4. The download will be very slow, shown in kb/s (doesn't even reach 1 Megabit/s)

**Expected behavior**
Downloading Should be faster than what it is

**Screenshots**

**Additional info (please complete the following information):**
 - OS: Windows 10, latest version
 - Application version: Latest (2.3.1 for github, 2.2.2 for MS Store)
 - Application type: Applies to all of them.

**Comment by Radplay** [comment]
Also, I recently reinstalled Windows, and i have TPM 2.0 enabled in my PC's UEFI.
