### ISSUE TITLE
Subscribe to channels

### ISSUE THREAD

**Issue by harrydevs2021** [jely2002/youtube-dl-gui#232]
Could there be a feature to subscribe to, or at least bookmark channels, and possibly show a notification when new videos are posted?

**Comment by Silver-Volt4** [comment]
This is very hard to do without YouTube's API, projects like NewPipe have struggled with this for long as well. The best workaround would probably be to use something like IFTTT.

**Comment by jely2002** [comment]
This app is made to download videos. Not to poll YouTube for when new videos and such get posted. YouTube isn't the only service that this tool can download videos from!
Because of this and the reason Silver-Volt4 gave, I will not be adding this anytime in the recent future.
