### ISSUE TITLE
No videos in folder

### ISSUE THREAD

**Issue by Sogl** [jely2002/youtube-dl-gui#233]
App installed from Brew:
```console
~ brew install --cask open-video-downloader
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask-versions).
==> Updated Casks
Updated 1 cask.

==> Downloading https://github.com/jely2002/youtube-dl-gui/releases/download/v2.3.1/Open-Video-Downloader-2.3.1.dmg
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/252325835/4b071752-0b1
######################################################################## 100.0%
==> Installing Cask open-video-downloader
==> Moving App 'Open Video Downloader.app' to '/Applications/Open Video Downloader.app'
🍺  open-video-downloader was successfully installed!
➜  ~ 

```

I added 2 videos, the program writes that the download is complete:
![image](https://user-images.githubusercontent.com/7556290/141008622-78e64358-1b23-4ba1-ab61-5bf8950d4f88.png)

but there are no files in the folder. Show file in folder and Open file buttons do nothing.

Log:
```
[youtube] cNuPZbruWE8: Downloading webpage

[download] Destination: /Volumes/DATA//HOMM4/Dirt Lands_Hope/Heroes Of Might And Magic IV - Dirt Theme Classical Guitar Cover-(1080p25).f137.mp4

[download] 0.0% of 21.53MiB at 3.54KiB/s ETA 01:43:49

[download] 0.0% of 21.53MiB at 10.61KiB/s ETA 34:37

[download] 0.0% of 21.53MiB at 24.75KiB/s ETA 14:50

[download] 0.1% of 21.53MiB at 53.00KiB/s ETA 06:55

...

[download] 99.7% of 21.53MiB at 68.44KiB/s ETA 00:00

[download] 100.0% of 21.53MiB at 68.78KiB/s ETA 00:00

[download] 100% of 21.53MiB in 07:19

[download] Destination: /Volumes/DATA//HOMM4/Dirt Lands_Hope/Heroes Of Might And Magic IV - Dirt Theme Classical Guitar Cover-(p).f251.webm

[download] 0.1% of 1.79MiB at 6.58KiB/s ETA 04:38

[download] 0.2% of 1.79MiB at 19.70KiB/s ETA 01:33

...

[download] 98.2% of 1.79MiB at 68.74KiB/s ETA 00:00

[download] 100.0% of 1.79MiB at 68.93KiB/s ETA 00:00

[download] 100% of 1.79MiB in 00:27

[ffmpeg] Merging formats into "/Volumes/DATA//HOMM4/Dirt Lands_Hope/Heroes Of Might And Magic IV - Dirt Theme Classical Guitar Cover-(1080p25).mp4"

Deleting original file /Volumes/DATA//HOMM4/Dirt Lands_Hope/Heroes Of Might And Magic IV - Dirt Theme Classical Guitar Cover-(1080p25).f137.mp4 (pass -k to keep)

Deleting original file /Volumes/DATA//HOMM4/Dirt Lands_Hope/Heroes Of Might And Magic IV - Dirt Theme Classical Guitar Cover-(p).f251.webm (pass -k to keep)

[ffmpeg] Adding metadata to '/Volumes/DATA//HOMM4/Dirt Lands_Hope/Heroes Of Might And Magic IV - Dirt Theme Classical Guitar Cover-(1080p25).mp4'

Download finished

```

Open Video Downloader 2.3.1
Mac OS Catalina 10.15.7

**Comment by Sogl** [comment]
I found strange folder on my DATA disk:
![image](https://user-images.githubusercontent.com/7556290/141015622-3a8cc505-61dc-4047-bfba-c3bc5ece5e2e.png)

Where all my files:
![image](https://user-images.githubusercontent.com/7556290/141015669-057a9aae-d3bb-4465-b4d8-397fe0e8d3e0.png)

If you select the Downloads folder, then everything works great

**Comment by jely2002** [comment]
That's quite strange behavior, I'm not sure why this could have happened. Thanks for reporting it anyways.
Luckily you did find your files. I will close this as it's mostly resolved.

**Comment by Sogl** [comment]
The problem is not solved, writing to the Downloads folder is a workaround. 

Maybe it makes sense to find what is the reason?

**Comment by jely2002** [comment]
I am unable to research this any further. I don't have a mac that I can use. And the standard value for the download location is retrieved from the electron API, using this method: https://www.electronjs.org/docs/latest/api/app#appgetpathname to get the downloads folder.

Perhaps I misunderstood and you mean that it adds this weird folder when you set the file location to your data drive?

**Comment by Sogl** [comment]
When I add a non-system DATA disk (Mac OS Extended filesystem) as a download folder, a strange folder is created not in the selected location, but in the root of this disk.
