### ISSUE TITLE
Playlist order and choosing subtitle

### ISSUE THREAD

**Issue by BEST8OY** [jely2002/youtube-dl-gui#234]
Hello
When I add a playlist, the playlist videos are not in order the way they are in YT website playlist?
I want to download them in order.
Some option for this?

And

For example when I add a playlist with 30 video; it is frustrating to go to each video and choose "English" subtitle for each video. ( at least I have to do this because it doesn't download the subtitle of videos just with "subtitle icon without slash on it" I mean I have to go to each video sub settings and enable "download subtitles" and even choose "English" which is really frustrating to do for each video )
In my case English Subs are auto generated but either way I have to choose "English" for having subtitle for each video.
[My CASE](https://www.youtube.com/watch?v=AjdUxCnAXJw&list=PLXL_lTSgbB_VCpVgy5QyEHBb7wPdT7G7P)
If you could add an option in app settings for default settings of subtitle and not choosing A certain Language for each video it would be great.

**Comment by taqui1992** [comment]
I'm having this exact same issue and would love to have the playlists videos download in the order of the original playlist.
I need to offline an entire course of videos with subtitles and there are over 100 videos that I need to be able to watch with subtitles. It's very time consuming to go to each video and check 'download subtitles' and then also select the language. 
There should be an option to automatically include the subtitles and the default language.
