### ISSUE TITLE
MP4 File Format output FAIL

### ISSUE THREAD

**Issue by alexvoz** [jely2002/youtube-dl-gui#238]
**Describe the bug**
When I try download video in MP4 format, download FAIL

**To Reproduce**
1. Go to 'Settings - Output Format - MP4'
2. Click on 'Download Any Video'
3. See error ERROR: Postprocessing: Stream # 1:0 -> # 0:1 (copy)

**Screenshots**
https://postimg.cc/hJGtnDPg

**Additional info (please complete the following information):**
 - OS: Windows 10 x64 (all updates)
 - Application version 2.4.0
 - Application type - installer

**Additional context**
MKV format works good

**Comment by BeeBobin** [comment]
Response to this issue on this thread: https://github.com/jely2002/youtube-dl-gui/issues/236

**Comment by jely2002** [comment]
This is a duplicate of #236. Closing as such.
