### ISSUE TITLE
How are AppImages updated?

### ISSUE THREAD

**Issue by Mennaruuk** [jely2002/youtube-dl-gui#24]
I'm wondering how I can have AppImages updated whenever a new update comes out. Do I have to redownload everything? Or is it a simpler process?

**Comment by jely2002** [comment]
Hi Mennaruuk,
AppImages should auto-update. Sadly after some testing this feature appears to have been broken for a while now. I have applied a fix, starting with upcoming version 1.8.6 the app should auto-update on linux as well. I'm sorry for any inconvenience.

**Comment by Mennaruuk** [comment]
No, thank you very much!!! I love AppImages, and auto update or at least an option to alert when a new update is here would make life much easier.

**Comment by jely2002** [comment]
This is now all sorted out in v1.8.6! Closing.
