### ISSUE TITLE
Youtube not working

### ISSUE THREAD

**Issue by Mitezuss** [jely2002/youtube-dl-gui#256]
yt-dlp.exe is not working, with youtube (right now)
![0](https://user-images.githubusercontent.com/35956777/144944979-7e3a347f-e514-4115-8898-83d71c9715b2.png)

but yt-dl.exe is working
![1](https://user-images.githubusercontent.com/35956777/144945108-a5b7a727-fe43-4bea-988b-198b52d7d1c0.png)

@jely2002 
**So, can add a option to select what .EXE to use to manage the downloads ?**

**Comment by jely2002** [comment]
Hello, is this still relevant?

It is hard to just have a toggle for which library to use, since they return different objects and the GUI is now changed for optimal compatibility with yt-dlp.
