### ISSUE TITLE
Fix EACCESS on first start / Set YouTube-dlp to executable after download  

### ISSUE THREAD

**Issue by StefanLobbenmeier** [jely2002/youtube-dl-gui#262]
> About you getting an EACCESS. This is probably because the downloaded file isn't marked as executable yet. I set it to executable with `chmod` on start of the app, so this would be another bug. 

_Originally posted by @jely2002 in https://github.com/jely2002/youtube-dl-gui/issues/259#issuecomment-997405353_

**Comment by brenard** [comment]
Same problem here and same issue : After `chmod +x` on binaries downloaded on first startup (`ffmpeg`, `ffprobe` and `yt-dlp-unix`), problem is fixed.

Furthermore, binaries have permissions `0666`, which is a little too permissive : `0755` (or `0750`) is more suitable.
