### ISSUE TITLE
Error popup TypeError: Object has been destroyed at ClipboardWatcher.resetPlaceholder

### ISSUE THREAD

**Issue by StefanLobbenmeier** [jely2002/youtube-dl-gui#263]
**Describe the bug**
Sometimes when Open Video Downloader is running in the background I get a popup that says

```
A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Object has been destroyed
at ClipboardWatcher.resetPlaceholder (/Applications/Open Video Downloader.app/Contents/Resources/app.asar/modules/ClipboardWatcher.js:17:18)
at ClipboardWatcher.poll (/Applications/Open Video Downloader.app/Contents/Resources/app.asar/modules/ClipboardWatcher.js:30:26)
at Timeout._onTimeout (/Applications/Open Video Downloader.app/Contents/Resources/app.asar/modules/ClipboardWatcher.js:12:46)
at listOnTimeout (internal/timers.js:549:17)
at processTimers (internal/timers.js:492:7)
```

**To Reproduce**
No idea unfortunately.
Happens randomly while running in the background. I have seen it on macOS Sierra and Big Sur.

**Expected behavior**
No errors 😄 

**Screenshots**
![image](https://user-images.githubusercontent.com/36509607/146846637-90b74077-38f1-4d78-9fc7-a9fd9fcacd34.png)

**Additional info (please complete the following information):**
 - OS: macOS Sierra, Big Sur
 - Application version 2.4.0
 - Application type: .dmg from Github

**Additional context**

**Comment by StefanLobbenmeier** [comment]
Looking at the source code I think I figured out how to reproduce.

1. Click on the close button (The process stays active)
2. Wait some time

Not quite sure what the best solution would be. On macOS having an application closed still has it running in some kind of standby in the task bar:
![image](https://user-images.githubusercontent.com/36509607/146848080-4e61cd41-342b-4855-90fe-42811b69134c.png)

So when now the ClipboardWatcher acts on the Window it does not exist anymore.
So either this can be fixed by checking if the window is still active somehow, or perhaps the behaviour for the close button can be changed.

**Comment by jely2002** [comment]
Thank you for your thorough investigation. A simple null check will be sufficient to prevent this from happening.
