### ISSUE TITLE
Add support for yt-dlp

### ISSUE THREAD

**Issue by ILG2021** [jely2002/youtube-dl-gui#266]
Hello, may you add support for yt-dlp as a backend, because the official youtube-dl is restricted to the download speed. yt-dlp can download as the fast speed.

**Comment by EricE549X** [comment]
already done, install v2.4.0

**Comment by What-Zit-Tooya** [comment]
> Hello, may you add support for yt-dlp as a backend, because the official youtube-dl is restricted to the download speed. yt-dlp can download as the fast speed.

duplicate https://github.com/jely2002/youtube-dl-gui/issues/151
its already included and supported
