### ISSUE TITLE
Download from different websites

### ISSUE THREAD

**Issue by Fabian9799** [jely2002/youtube-dl-gui#27]
**Is your feature request related to a problem? Please describe.**
If i want to download videos from another platform for example twitter or vimeo i have to go to another tool to download it

**Describe the solution you'd like**
An option to download videos from other websites

**Describe alternatives you've considered**
I used [this](https://mrs0m30n3.github.io/youtube-dl-gui/) one in the past and it worked great

**Comment by jely2002** [comment]
Hi Fabian,
With how the application is currently written it is impossible for me to add more websites.
I am however completely rewriting the app, so I will definitely add more websites you can download from.
The new rewritten version of the app will not release anytime soon sadly. As I don't have a lot of time on my hands right now.

**Comment by lclem** [comment]
I also found very limiting that this GUI supports only youtube, considering that youtube-dl in fact supports many more platforms out of the box :)
