### ISSUE TITLE
How is it so fast?

### ISSUE THREAD

**Issue by UltraBlackLinux** [jely2002/youtube-dl-gui#271]
**Describe the question you have.**
... How is this so fast? This seems to just use youtube-dl, but I have used youtube-dlg before and that always downloaded the whole video just keep the audio when setting it to just audio, why is this program not doing it the same way? Did you modify youtube-dl or did youtube-dlg fail to update it?

**Additional context**
Amazement.

**Comment by EricE549X** [comment]
jelle switched the foundation of this app to yt-dlp in november which has been maintained since june 2021 unlike youtube-dl.

**Comment by UltraBlackLinux** [comment]
Oh what? I didn't know ytdl hat died - why though?

**Comment by EricE549X** [comment]
i said "at the time." they pushed out an [update](https://github.com/ytdl-org/youtube-dl/releases/tag/2021.12.17) a month after this app switched to yt-dlp.
