### ISSUE TITLE
Menu setting

### ISSUE THREAD

**Issue by ivor1** [jely2002/youtube-dl-gui#278]
**Describe the solution you'd like**
Add a function to specify the folder for the cache. I am using virtual ramdisk so as not to burden my ssd disk.

**Comment by jely2002** [comment]
This app disables caching completely. By setting the `--no-cache-dir` flag. So there is no cache being stored.
The only thing temporarily stored are .part files that are part of the download and later get merged into the final video.
It is currently not possible to put these files somewhere else.
