### ISSUE TITLE
option to download tiktok videos with watermark

### ISSUE THREAD

**Issue by EricE549X** [jely2002/youtube-dl-gui#280]
**Is your feature request related to a problem? Please describe.**
unlike most people, i appreciate watermarks because they help find the original creator. the current version of OVD downloads tiktok videos without the watermark, hence why i've used v2.3.1 of OVD to download tiktok videos. unfortunately, that version doesn't seem to work anymore.

**Describe the solution you'd like**
if yt-dlp allows it, i'd like the option to download tiktok videos with the watermark.

**Describe alternatives you've considered**
literally every tiktok downloader out there omits the watermark. there are no alternatives.

**Additional context**
thanks for all the work you do <3

**Comment by i8cczshd** [comment]
right click->save video as

**Comment by EricE549X** [comment]
holy shit it actually works
