### ISSUE TITLE
How can I switch to YT-DLP using the AppImage?

### ISSUE THREAD

**Issue by swcrazyfan** [jely2002/youtube-dl-gui#283]
I've been using Open Video Downloader fine on my mac, but I've recently set it up on my Ubuntu VM so I can download things in the background. I'd like to use YT-DLP, but I can't figure out how to do that. Someone gave instructions for doing this on Windows, but that doesn't seem to be what to do with the Linux AppImage.

Can I also modify the YT-DLP or YouTube-DL config while using the AppImage? Thanks!

Thanks for your help in advance!

**Comment by jely2002** [comment]
Hello! The latest version of the AppImage (2.4.0) should use YT-DLP by default. Using a config is currently disabled as it can clash with certain options the app uses.
