### ISSUE TITLE
AppImage on Linux, downloaded files have wrong permissions

### ISSUE THREAD

**Issue by fidian** [jely2002/youtube-dl-gui#286]
**Describe the bug**
I get immediate errors when trying to download playlists and videos.

**To Reproduce**
1. Delete `~/.youtube-dl-gui` if it exists.
2. Use the current AppImage build.
3. Attempt to download any video or playlist.

**Expected behavior**
Download works.

**Additional info (please complete the following information):**
 - OS: Ubuntu Linux, 21.10
 - Application version: 2.4.0
 - Application type: AppImage

**Additional context**
To fix:
1. `cd ~/.youtube-dl-gui`
2. `chmod 755 ffmpeg ffprobe yt-dlp-unix`

**Comment by guemidiborhane** [comment]
Same issue here, building from source

**Comment by jely2002** [comment]
Thank you for the report, this was fixed in #264. It has however not been released yet. It will be releasing relatively soon.
