### ISSUE TITLE
can't cancell downloading

### ISSUE THREAD

**Issue by lambdaxyzt** [jely2002/youtube-dl-gui#29]
can't cancell downloading progress

**Comment by jely2002** [comment]
Hi lambdaxyzt,
v1.8.7 has no way to cancel downloading once it has started. Of course you can always close the app ;).
v2.0.0 which is in the makings right now will have this capability, along with a lot more new features and an all new GUI.
I expect this version to come out sometime in March.
Closing this issue for now.
