### ISSUE TITLE
pausing downloading item

### ISSUE THREAD

**Issue by lambdaxyzt** [jely2002/youtube-dl-gui#30]
pausing downloading item or playlist and resume capability

**Comment by jely2002** [comment]
Hi lambdaxyzt,
I do not intend to add this feature to v2.0.0. When you cancel a download and it was already lets say 40% done, it will just resume from there the next time you try to download it. Besides, I don't think a pause button would be that usefull compared to how much work it would cost to implement it.
Closing for now.
