### ISSUE TITLE
Multithreaded Youtube Downloads

### ISSUE THREAD

**Issue by NinekoTheCat** [jely2002/youtube-dl-gui#32]
I think It could considerably increase the speed of file downloads when dealing with playlists. Furthermore, It could potentially improve speeds on multicore setups since multithreaded downloads tend to saturate the network connection and go faster than single file downloads.

**Comment by jely2002** [comment]
Hi, NinekoTheCat,
The app already uses multithreaded downloading when downloading playlists. Up to 4 child processes get spawned that each download videos. The code is for this whole mechanism is [right here](https://github.com/jely2002/youtube-dl-gui/blob/a7676ffc8959c3242f2bc229a7d48a91c4cebc87/modules/playlist.js#L263). So downloading playlists is 4 times as fast. In the next major release of this app, v2.0.0. There will be a setting where you can select the maximum amount of child processes being used.

If you have anymore questions let me know!
