### ISSUE TITLE
Option for download video with thumbnail

### ISSUE THREAD

**Issue by SuperHellCat** [jely2002/youtube-dl-gui#36]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jely2002** [comment]
Hi SuperHellCat,

In version 2.0.0 that will be releasing soon, I have added a setting to download thumbnails along with the videos. I have also added a function so you can download only the thumbnail to a location of your choosing.

This is how downloading only the thumbnail looks like in v2.0.0:

<img alt="preview of downloading a thumbnail" src="https://i.imgur.com/yxtxUBp.png" height="500">

Let me know if you have any more questions regarding this feature.
