### ISSUE TITLE
Forgot How to V Open youtube-dlg

### ISSUE THREAD

**Issue by muttleytm** [jely2002/youtube-dl-gui#38]
I installed the new version of youtube-dlg in January or february of 2021 on Linux mint 20.  It worked fine.  I went to open it but did not find it or the icon in the installed apps.

I try typimg youtube-dlg in the terminal and it doesn't work.  I can't find a file with that name.  At first if I looked for it it would open tartube.  It wassupposed to be a gui for youtube-dl, but I never got it to work.

Looking over things I see I dowonladed as a disk image file.  That may be what I need to look for.

If I can find out how to open it I'll just make a launcher.  Why there is no icon for the app I have no idea

I'm sure I didn't just dream I installed it and know I didn't uninstall it.  For now I'll just use youtube-dl command line.  Maybw someone can offer some suggestions.  I'm tired at the moment and have other things to do.

TIA

**Comment by jely2002** [comment]
Hi muttleytm,

> I installed the new version of youtube-dlg

This application has no installer for linux. You download an .appImage file that you can run somewhat like a portable executable.


> I try typimg youtube-dlg in the terminal and it doesn't work.

Launching this app from the terminal with `youtube-dlg` does not work. You have to run the .appImage from the terminal or by clicking it.


> I went to open it but did not find it or the icon in the installed apps.

If you lost the appImage file just redownload it from the [releases](https://github.com/jely2002/youtube-dl-gui/releases/latest) on github.

Maybe you confused this app for another app, or maybe I do not understand your question that well. But I have tried answering it anyway. Let me know if you have any further questions. I will be closing the issue for now.
