### ISSUE TITLE
error!  unhandled error (execa)

### ISSUE THREAD

**Issue by Condobloke** [jely2002/youtube-dl-gui#416]
https://jely2002.github.io/youtube-dl-gui/    ....added....produces error in title (unhandled error execa)

To reproduce, open video downloader.
paste youtube url into box at top....click on +
This immediately produces the error
I did "submit a report" a number of times there.
The expected behaviour at that time is for the audio or video to commence downloading. (I did not get that far, so I may be missing a few steps here!)
The full error (from that page is : 
![image](https://user-images.githubusercontent.com/17040420/188297756-4763a6bc-e525-4d34-b5d4-f2488b308561.png)

Linux Mint 21.

Vid downloader version: 2.4.0
![2022-09-04_14-45](https://user-images.githubusercontent.com/17040420/188297843-c879bc0f-0a16-423c-9597-8c3189d91bac.png)

I downloaded this as an appimage......right clicked...selected properties....and altered the permissions to allow executing as a program. The app then opened easily 
![latest](https://user-images.githubusercontent.com/17040420/188298001-8e5bc7e1-3842-40c0-8761-97ad882ea87d.png)

**To Reproduce**

**Expected behaviour**

**Screenshots**

**Additional info (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Application version [e.g. 1.8.4] (the version can be found in the settings menu)
 - Application type [e.g. portable, installer, Microsoft Store]

**Additional context**

**Comment by Condobloke** [comment]
I chose to go with Video Downloader  ....which I found in Linux Mint 21's Software Manager.

**Comment by mid-ff-play16** [comment]
> I chose to go with Video Downloader ....which I found in Linux Mint 21's Software Manager.

Video Downloader - this is the one that VDL - Video Downloader?

**Comment by Condobloke** [comment]
https://github.com/flathub/com.github.unrud.VideoDownloader

https://github.com/Unrud/video-downloader
