### ISSUE TITLE
How do you set the ffmpeg path?

### ISSUE THREAD

**Issue by Downloaddave** [jely2002/youtube-dl-gui#441]
Hey Guys, 

Hopefully this will be a quick question. 
**Reproduction Steps**
When I try to use try to use the application I get the following error message:

ERROR: Postprocessing: ffprobe and ffmpeg not found. Please install or provide the path using --ffmpeg-location

I checked if I had ffmpeg installed on my MacBook Pro (14-inch, 2021) macOS Monterey 12.4 by opening the terminal and located where ffmpeg is installed:

```
$ which ffmpeg
/usr/local/bin/ffmpeg
```

Now that I know the path of ffmpeg I'm not sure where to set the path. I went to the "Settings" icon and went into the "App Settings" page but didn't find a place where I can set the ffmpeg path.

As for a terminal setting I'm not sure what command to use to set the path do I run the following?

`$ youtube-dl-gui --ffmpeg-location /usr/local/bin/ffmpeg`

Is there a way to set the path that I'm not aware of in the GUI?
Is there a command line way to set the path?
Or
What path is the ffmpeg _supposed_ to be? (maybe I can move ffmpeg to that location?)

Thanks in advance!

**Comment by hangman1998** [comment]
one dummy answer would be to remove `ffmpeg` from `PATH`. this would result in a fresh download of the needed libraries
i.e. `ffmpeg`, `ffprobe`, ... in a location where the app knows about.
although the current release version cannot fetch `yt-dlp` (due to a bug)
check Issue #436  for that matter.

**Comment by Downloaddave** [comment]
@hangman1998 Thank you! I appreciate the super fast response. Seems to have worked by uninstalling ffmpeg then installing the Open Video Downloader again.

I'll be sure to check for updates and get the latest once this bug #436 is resolved. 

Mucho Gracias

**Comment by Think-42** [comment]
I got the same error 🙈 But I want able to fix it.

I deinstalled ffmpeg and then reinstalled the application. I even saw in the status bar that ffmpeg was installed by the application again.

But I still have the error. Is there a way to link in manually?

**Comment by Think-42** [comment]
Nevermind...
turning my computer off and on again did the job.
