### ISSUE TITLE
Flathub Packaging

### ISSUE THREAD

**Issue by BeatLink** [jely2002/youtube-dl-gui#45]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be great if this app could be packaged with flatpak and released with flathub. It would then make it immediately accessible to hundreds of linux distros that support flatpak

**Describe alternatives you've considered**
Existing packaging formats such as deb and rpm are limited in terms of distro support. Appimage is good but lacks the dependency and systems integration of an actual package manager. 

**Additional context**

**Comment by jely2002** [comment]
Hi BeatLink,

Flatpak support is currently still experimental in electron-builder (this is what this app uses to build releases). The app requirements for submitting an app to Flathub are quite extensive as well. For the above reasons I am reluctant of adding Flatpak support as of now. I will however be following the issue about Flatpak (electron-userland/electron-builder#512) and the associated pull requests closely. I might reconsider adding support for Flatpak when this target has matured within electron-builder.

If you have more questions, please let me know.
I will be closing this issue for now.
