### ISSUE TITLE
Doesn't work anymore on MacOS

### ISSUE THREAD

**Issue by ddcado** [jely2002/youtube-dl-gui#457]
Hello,
Since few weeks I can't download from youtube. I sent you a bug report using thé buttons on the app.
I think it is something dealing with yt-dl. I tried to reinstall it and when i used it I discover that m'y MacOS use only Python3 and it's not possible to use or create a link /usr/local/bon/python
Then i managed to change " python" to "Python3" on youtube-dl and now yt-dl works correctly.
I think you need to manage this point on your app, checking environment on installing and change the first Line on yt-dl in case python or Python3
Have a nice day.

**Comment by StefanLobbenmeier** [comment]
Hey :) can you try with my fork https://github.com/StefanLobbenmeier/youtube-dl-gui? Which version of macOS and of open video downloaded are you using?

**Comment by StefanLobbenmeier** [comment]
@ddcado did that end up working for you?

**Comment by ddcado** [comment]
> @StefanLobbenmeier  
Hello,
excuse me for the delay. I've just tried your last 2.4.8.dmg,
it seems to be fine, I managed to download video.
thanks
