### ISSUE TITLE
Save and restore the task list

### ISSUE THREAD

**Issue by chengstone** [jely2002/youtube-dl-gui#46]
run this app every time the task list will be lost, I can't remember all site address that I download, please add this feature like other download apps did.

**Comment by jely2002** [comment]
Hi chengstone,

As I can see a potential use case for this feature. I will add it to the 'New features' project.  I currently have no indication as to when this feature will be released.

If you have any more questions, please let me know.

**Comment by jely2002** [comment]
This feature has now been implemented, it will release in version 2.1.0. Closing the issue for now.
