### ISSUE TITLE
Execa error (Encoding Error is what it seems)

### ISSUE THREAD

**Issue by apage-pi** [jely2002/youtube-dl-gui#462]
# Got an execa error (I have yt-dlp installed in the correct location(s), it isn't the issue here).
![image](https://user-images.githubusercontent.com/72623953/213337473-a58337a0-a2cb-4570-87b2-315b23ae80fb.png)
OS: Ubuntu 22.04 LTS
Just downloaded latest version.
Please help me here, I can't find an answer.

**Comment by StefanLobbenmeier** [comment]
Feel free to use the fixed version on my fork: https://github.com/StefanLobbenmeier/youtube-dl-gui

**Comment by sikhenevai** [comment]
Probably you have downloaded wrong file. You may download file named only "yt-dlp" from https://github.com/yt-dlp/yt-dlp/releases , **size 2.57MB** and rename it to "yt-dlp-unix" and paste it to that directory.

**Comment by apage-pi** [comment]
Thank you. I can now close this issue.
