### ISSUE TITLE
'Binaries missing/corrupted' Error

### ISSUE THREAD

**Issue by TheJCB** [jely2002/youtube-dl-gui#463]
The error says I should restart the app and disable antivirus, but this doesn't work. Not sure what to do here.
![image](https://user-images.githubusercontent.com/73620197/214723891-f82d44ac-1de0-407e-b8b3-84017e9158d7.png)

**Comment by ghOSt-XIII** [comment]
Same issue here

**Comment by carterfyi** [comment]
Workaround: Fetch the yt-dlp binary manually. (This solution is likely Windows-only, but the problem may also be Windows-only :P)

1. [Download the precompiled binary yt-dlp.exe](https://github.com/yt-dlp/yt-dlp/releases/)
2. Drop it into the this folder, taking care to substitute {USER} to match your home directory:
  `C:\Users\{USER}\AppData\Local\Programs\youtube-dl-gui\resources\app.asar.unpacked\binaries`
3. Close & Reopen OVD

**Comment by TheJCB** [comment]
Workaround worked perfectly - thank you!

**Comment by ghOSt-XIII** [comment]
Yep, worked on my end as well. Much appreciated,
