### ISSUE TITLE
Selecting Preferred Video/Audio Codec

### ISSUE THREAD

**Issue by KleinReveche** [jely2002/youtube-dl-gui#47]
I love the look and feel of this software, but I have a specific need in downloading youtube videos. I would like to ask to have an option in the settings that can open advanced features/settings. The Advanced Features/Settings could include selecting the resolution and codec in selecting video and audio without compromising the usability and simplicity for beginners.

Also I would like to ask the youtube-dl -F results to have appear maybe in a button in the info section.

I am conscious in the size of the video/audio because I have a metered connection. I usually use VP9+OPUS but sometimes I use AVC1+OPUS in my videos depending on what video format is smaller in a given resolution.

I appreciate your work, Thanks in Advance.

**Comment by jely2002** [comment]
Hi Klein Reveche,
> The Advanced Features/Settings could include selecting the resolution and codec in selecting video and audio without  compromising the usability and simplicity for beginners.

I will start working on this feature, as I can see a use case for this.

> Also I would like to ask the youtube-dl -F results to have appear maybe in a button in the info section.

This would be a bit harder, and in my opinion not necessary if I just list all the resolutions and codecs in the list. So I won't be adding this.

If you have anymore questions, feel free to ask.

**Comment by KleinReveche** [comment]
Thanks for responding! I really appreciate that.

As for the second request, I understand, thinking about it, it's harder to do so that's okay.

**Comment by L0Lock** [comment]
> This would be a bit harder, and in my opinion not necessary if I just list all the resolutions and codecs in the list. So I won't be adding this.

Sounds great, and also future-proof. [AV1 ](https://www.youtube.com/watch?v=oAbB4dQOz4I)is coming, slowly but surely, it would be sad to miss it when available.

**Comment by jely2002** [comment]
This feature will be postponed to v2.2.0 since I do not have a lot of time on my hands right now.

**Comment by rugabunda** [comment]
Yes, it would be great to see choice offered between H264 and AV01 encoded video; AV01 is not currently compatible with popular video editing software such as premiere pro. One must chose MP4 container with H264 to avoid transcoding; Thus I am forced to switch to 4Kdownloader for many videos, which offers these options. Thanks for your consideration, and for offering such an excellent little program, its probably the best video downloader out there other than 4kdownloader and Video DownloadHelper

**Comment by EricE549X** [comment]
this would also be great because i have a mac, and i would need to have all downloads converted to AAC/H.264 since opus/vp09 isn't supported.

**Comment by jely2002** [comment]
This has now been implemented! I will be merging the PR (#143) soon.
After the merge, this feature will be released in the next feature update, possibly 2.3.0.

More information about how this feature will work is provided in the PR (#143).
