### ISSUE TITLE
Selecting filename format

### ISSUE THREAD

**Issue by Enduser-only** [jely2002/youtube-dl-gui#48]
It would be very convenient to add additional filename format settings that would automatically add elements such as channel name, quality, and ID to the saved filename with out having to do so manually. An example of how this is done can be seen in "Youtube-DLG." Images attached show screenshots of the filename format setting from "Youtube-DLG." 

Thank you. 

![132fgh5](https://user-images.githubusercontent.com/39422267/116534185-0efe3180-a897-11eb-8dbe-19d6c8220ee4.png)
![dfg1d](https://user-images.githubusercontent.com/39422267/116534192-11608b80-a897-11eb-9bd3-113bbf09deaf.png)

**Comment by jely2002** [comment]
Hi Enduser-Only,
I can definitely see a good use of this feature. Will add it to the v2.1.0 roadmap.

**Comment by jely2002** [comment]
This feature has been added in v2.1.0.
