### ISSUE TITLE
Error postprocessing, ffmepg location not found

### ISSUE THREAD

**Issue by naftonaf** [jely2002/youtube-dl-gui#486]
Hello,
When downloading a video, an error appear.
"Error postprocessing, ffmepg location not found"

I'm on Windows 10 22H2

Report ID: 478208ae

![2023_04_11_12_45_02_Open_Video_Downloader](https://user-images.githubusercontent.com/22202942/231137855-0a13d21c-3876-4fed-ab4e-af8b0a1f94df.png)

**Comment by naftonaf** [comment]
I've found how to repair !
Just download ffmpeg.exe and place it \AppData\Local\Programs\youtube-dl-gui\resources\app.asar.unpacked\binaries

**Comment by afraca** [comment]
Your solution is right, great job @naftonaf! 
I highly recommend you switch to a maintained fork. This version of Open Video Downloader hasn't seen activity in two years. The fork I'm using is this one:
https://github.com/StefanLobbenmeier/youtube-dl-gui

It got a release as recent as yesterday and has worked a lot better for me.
