### ISSUE TITLE
Error! Binaries missing/corrupted.

### ISSUE THREAD

**Issue by Ahmed-Soli** [jely2002/youtube-dl-gui#490]
I downloaded V2.4.0 windows installer and installed [Microsoft Visual C++ 2010 Redistributable Package (x86)](https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe) as instructed but I'm getting this error `Error! Binaries missing/corrupted.`  with this URL [Microservices Architecture in Arabic](https://www.youtube.com/playlist?list=PLgAqrVq84PDdfiDow3YVsgc1q34JD415Z)

Note:
- I tried running the app as Administrator .
- I tried other playlists links and it always returns the same error

![image](https://user-images.githubusercontent.com/39798205/234568658-59680d34-0390-4a2d-b085-8ea2d9127423.png)

**Comment by l0gansw0rld** [comment]
i am also having this issue! took the same steps. hope it is fixed soon thank you for the work you do!

**Comment by LillyBird69** [comment]
Check thread #483, it solved the problem for me.

**Comment by Ahmad-Alkaf** [comment]
I got the same error with every Youtube URL I've tried `Error! Binaries missing/corrupted.
Please restart the app and disable antivirus.` I disabled antivirus and restarted the app. The same error shows up

**Comment by Ahmed-Soli** [comment]
downloading [this version](https://github.com/StefanLobbenmeier/youtube-dl-gui/releases/tag/v2.4.10) solved the problem

**Comment by Ahmed-Soli** [comment]
> Check thread #487, it solved the problem for me.

thank you, it did fix it.
