### ISSUE TITLE
This repo is dead and should not exist

### ISSUE THREAD

**Issue by indig0F10w** [jely2002/youtube-dl-gui#494]
As the title says, this repo is dead and should not exist. It only makes confusion with regularly updated and WORKING version of https://github.com/StefanLobbenmeier/youtube-dl-gui.

Every single issue reported is with yt-dl-gui and now famous Unhandled error.

The original author has not responded to issues for a loooooong time and the author of working version has to respond here, on the dead repo.

**Comment by ElijahNemr** [comment]
Thank you for posting this, I didn't know development migrated. I agree, this repo should be marked "obsolete" or some equivalent.

**Comment by adarsh-chakraborty** [comment]
Thanks

**Comment by himyjan** [comment]
https://github.com/jely2002/youtube-dl-gui/issues/354#issuecomment-1127269708

or 

https://github.com/StefanLobbenmeier/youtube-dl-gui/releases

**Comment by rahadiannorman** [comment]
> As the title says, this repo is dead and should not exist. It only makes confusion with regularly updated and WORKING version of https://github.com/StefanLobbenmeier/youtube-dl-gui.
> 
> Every single issue reported is with yt-dl-gui and now famous Unhandled error.
> 
> The original author has not responded to issues for a loooooong time and the author of working version has to respond here, on the dead repo.

Thank you for letting us know, btw does anyone know which version is that still working for now?

**Comment by indig0F10w** [comment]
Yes, uninstall whatever version you have and install the latest from
Stefan's repo. Or you can go thru manual trouble with instaling yt-dl
dependency.

**Comment by DereC4** [comment]
Thanks for posting this; was not aware development had migrated

**Comment by Oppa-YA** [comment]
Thank you so much for letting me know that program still getting updates! I wish i knew this earlier.

**Comment by DereC4** [comment]
no way
