### ISSUE TITLE
Trouble Getting Program To Work

### ISSUE THREAD

**Issue by FrancoDaily** [jely2002/youtube-dl-gui#495]
Hello Everyone.
I keep getting the error Binaries missing/corrupted and asks me to restart the app and disable my antivirus?
I disabled my antivirus but still the same error!
Can someone please help me please. 
Using version 2.4.0. Downloaded from site.
Thank You!!!

**Comment by JWBstuhr** [comment]
This repository isn't updated anymore.
Try [this](https://github.com/StefanLobbenmeier/youtube-dl-gui).

**Comment by FrancoDaily** [comment]
> This repository isn't updated anymore. Try [this](https://github.com/StefanLobbenmeier/youtube-dl-gui).

Thank You.
This worked perfectly.
