### ISSUE TITLE
downlaod button not working

### ISSUE THREAD

**Issue by thaynos** [jely2002/youtube-dl-gui#50]
exactly what it says in title. the download button is greyed out even though all metadata is loaded. im downloading videos from my watch later playlist.

**Comment by jely2002** [comment]
Hi thaynos,

That's should not be happening. Does it work if you try it again or is it a consistent problem? When I try downloading my own watch later playlist it works fine. Do you receive any errors while downloading the metadata? If not, try pressing `CTRL+SHIFT+I` and upload a screenshot of the window that pops up, this allows me to see what may have happened.

If you have any further questions please let me know.

**Comment by thaynos** [comment]
![image](https://user-images.githubusercontent.com/83282129/116960201-c092cd80-acb0-11eb-97ee-85d0fc0b9f0f.png)
as you can see the download button is greyed out
but when i cleared the queue and restarted the downloading again it works
![image](https://user-images.githubusercontent.com/83282129/116960410-5595c680-acb1-11eb-90bc-35b68bc6aaa2.png)

**Comment by jely2002** [comment]
So from this example I can conclude that it only happens every so often?
I haven't been able to find a possible cause yet. 
 > Do you receive any errors while downloading the metadata? If not, try pressing CTRL+SHIFT+I and upload a screenshot of the window that pops up, this allows me to see what may have happened.

If you could answer the question above, it would allow me to investigate further.

**Comment by thaynos** [comment]
oh no sorry i forgot to ctrl shit i :( . yes it happens every so often

**Comment by thaynos** [comment]
![Screenshot (192)](https://user-images.githubusercontent.com/83282129/117192362-b24cca80-adf2-11eb-963b-e7887f8bbef8.png)
![Screenshot (193)](https://user-images.githubusercontent.com/83282129/117192370-b37df780-adf2-11eb-8097-1f1e5d80b971.png)
![Screenshot (194)](https://user-images.githubusercontent.com/83282129/117192373-b4168e00-adf2-11eb-9e3b-91a0c6ef9961.png)
![Screenshot (195)](https://user-images.githubusercontent.com/83282129/117192379-b4af2480-adf2-11eb-8765-39dd2279dbb5.png)
ive attatched the ctrl shift i ss

**Comment by jely2002** [comment]
I think I have identified the culprit and have applied a fix. The fix will ship in version 2.1.0.

Closing the issue for now.

**Comment by thaynos** [comment]
![image](https://user-images.githubusercontent.com/83282129/117269491-5cffd000-ae69-11eb-8bf6-f9666b2fa4e2.png)
uh it does not work at all anymore i cant download anything i even restarted the app and my pc
