### ISSUE TITLE
Read before posting issues, what is wrong with you?

### ISSUE THREAD

**Issue by indig0F10w** [jely2002/youtube-dl-gui#517]
Please, https://github.com/StefanLobbenmeier/youtube-dl-gui

**Comment by markjirousek** [comment]
Read what, where?

There is no bold information here on the main page that this repo has been abandoned.

If you had read issues on the new repo you would have seen that I indeed already had found it, but I had to dig in the past issues to find some comments with a link.

It's nice to you to provide the info and the link but there is nothing "wrong with us". 

Info hasn't been brought to the front.

**Comment by xmaxrayx** [comment]
sorry but did the author have another account ? or this another user?

**Comment by markjirousek** [comment]
This is another user pointing to a new repo (fork) from another user. Jely2002 disappeared apparently, so the project has been forked and has a new dev there.

**Comment by StefanLobbenmeier** [comment]
yeah I am a separate person - see also https://github.com/StefanLobbenmeier/youtube-dl-gui?tab=readme-ov-file#credit

**Comment by StefanLobbenmeier** [comment]
@indig0F10w I appreciate you making sure that people find my fork, but please make sure to keep it civil - this is an understandable mistake and will probably keep happening until we can get a pinned issue by the original author

**Comment by indig0F10w** [comment]
When it comes to posting about issues, the (unwritten?) rule is to check if someone else has already reported the problem to avoid duplicates.

In referring to "[Read before posting issues, what is wrong with you?](https://github.com/jely2002/youtube-dl-gui/issues/517)" I meant people not reading the very first post on the top of the [Issues page](https://github.com/jely2002/youtube-dl-gui/issues) and go immediately to posting a new and/or already reported issue.

It seems that despite my [initial post](https://github.com/jely2002/youtube-dl-gui/issues/494), several individuals have posted without taking the time to review existing reports. Some have even realized that this repository is no longer active and have closed their posts.

I should have used a less confrontational tone in my message, as it's clear that there is no intentional wrongdoing. It's simply a matter of not reading the titles on Issues page.

Since June 5, 2023, there have been ongoing discussions on various issues raised here, not counting Stefan's replies:
https://github.com/jely2002/youtube-dl-gui/issues/510
https://github.com/jely2002/youtube-dl-gui/issues/508
https://github.com/jely2002/youtube-dl-gui/issues/506
https://github.com/jely2002/youtube-dl-gui/issues/499
https://github.com/jely2002/youtube-dl-gui/issues/494

Moving forward, I will be closing any posts I've made redirecting to a new, [maintained repository](https://github.com/StefanLobbenmeier/youtube-dl-gui). This will help streamline the process and ensure that Stefan can focus his attention on two repositories resolving any outstanding problems or notifying users of completed fixes.

This will be my final communication in this repository, and I sincerely apologize if my previous messages came across as rude in any way.

Wishing everyone a pleasant day ahead.

Hail Satan!

**Comment by markjirousek** [comment]
Why did you close this issue? It was visible at the top of the Issues tab before, now it hidden under another tab. More people will be prompt to do the same mistake of thinking this repo may still be active. I really don't get what you are trying to achieve here.
