### ISSUE TITLE
mass download quality changer

### ISSUE THREAD

**Issue by thaynos** [jely2002/youtube-dl-gui#52]
theres only 2 presets for changing quality for all videos. i wish there was quality changing by resolution ex 1080p, 720p, etc.

**Comment by trymeouteh** [comment]
I would like to see all the quality options for video and audio when downloading

**Comment by thaynos** [comment]
> I would like to see all the quality options for video and audio when downloading

same

**Comment by jely2002** [comment]
Hi everyone,
I think it would be useful to add this as an opt-in setting because it can get messy if you have a lot of different videos.
Will start working on this when I have time, for now I'll add it to the roadmap of v2.2.0.

**Comment by thaynos** [comment]
2.20? is 2.10 finished?

**Comment by 8465231** [comment]
Just wanted to say that I am also needing a quality selection for this to be useful for me.

I want to download some channels but best quality tries to download massive 4k files that I have no use for and worst gives me 144p potato cam.

480p-720p would be the ideal mix of quality and size for my use case.

Jdownloader allows the selection of acceptable qualities in check boxes. You can leave out resolutions above and below what you want and it will automatically download the highest available out of the options to select. This works great but sadly it has a bug that only downloads 100 videos from a channel.

This has led me to search the web but something that can download the whole channel AND select the quality.

**Comment by jely2002** [comment]
This feature has now been added and will be released in the next feature update. Excuse me for the many re-tried commits. My GPG key would somehow not get recognized.
