### ISSUE TITLE
Download auto-generated subtitles

### ISSUE THREAD

**Issue by thaynos** [jely2002/youtube-dl-gui#53]
even though i selected the subtitles enabled option i almost never get it embed. it only happens for 1/50 videos. sometimes the subs are in srt and not embed, other times its normally embed. many of the videos i download already have english subtitles not auto generated. even then i would like to download auto generated subs.

**Comment by jely2002** [comment]
Hi thaynos,

Can you supply with example videos where the subtitle embed does not work? This way I can verify and test it and maybe fix it if it does not work as expect. Auto-generated subtitles will never get embedded by the way.

**Comment by thaynos** [comment]
oh i thought auto generated subs can get embed. in other ytdl gui it shows auto gen subs option thats why i thought of it.

**Comment by jely2002** [comment]
I guess I can enable the download of auto generated subtitles in this app as well. I'll add it to the roadmap for v2.1.0.

**Comment by trymeouteh** [comment]
+1 for subtitles option

**Comment by thaynos** [comment]
:D

**Comment by jely2002** [comment]
This feature has been added in v2.1.0.
