### ISSUE TITLE
prompt for deleting videos

### ISSUE THREAD

**Issue by thaynos** [jely2002/youtube-dl-gui#54]
add a prompt for when you are deleting videos that have not been fully downloaded
ie are you sure you want to delete this its still downloading something like that

**Comment by jely2002** [comment]
Hi thaynos,

Great idea. I will add it to the roadmap for version 2.1.0.

**Comment by thaynos** [comment]
yes sure what i had in mind was a new window but this is even better

**Comment by jely2002** [comment]
Alright, good to hear! This feature will be shipped in version v2.1.0. Closing the issue for now.

**Comment by thaynos** [comment]
also could u add a setting in the settings window to turn this feature on or off?
