### ISSUE TITLE
save configuration/settings

### ISSUE THREAD

**Issue by thaynos** [jely2002/youtube-dl-gui#56]
every time i close the app i have to change my settings again. and add the cookies.txt file again.
there should be a feature in which the settings are saved.

**Comment by jely2002** [comment]
Hi thaynos,
Are you perhaps using the portable version? In this version nothing will ever be saved, hence why it is portable.
If you are using the regular windows/linux/mac versions, all the stuff will be saved, this has been tested and should work just fine.

**Comment by thaynos** [comment]
i am as a matter of fact using portable version as i do not have admin privileges. however isnt there a way using a config file or soemthing?

**Comment by jely2002** [comment]
Sadly there is no way to use a config file. If you want the settings to be saved it is just easier to use the windows installer.

Closing the issue, since this is not a bug and the question has been answered.
