### ISSUE TITLE
automatic network recording?

### ISSUE THREAD

**Issue by thaynos** [jely2002/youtube-dl-gui#57]
for trouble shooting you always tell me to hit ctrl shift i. but whenever i hit ctrl shift i it tells me to reload and i cant send the ss of the issue.
![image](https://user-images.githubusercontent.com/83282129/117192702-17a0bb80-adf3-11eb-939d-dccd940dccab.png)

**Comment by jely2002** [comment]
What you are seeing is the network activity tab of the developer tools. What you are seeing is normal, when sending screenshots of the developer tools you need to be on the console tab. For more information on the developer tools [see the documentation](https://developer.chrome.com/docs/devtools/overview/).

Closing the issue for now.
