### ISSUE TITLE
date of upload in file name

### ISSUE THREAD

**Issue by bogna881** [jely2002/youtube-dl-gui#59]
I think a good feature for archival purposes would be able to include the date of upload in the file name so people do not have to manually enter it in

**Comment by jely2002** [comment]
Hi bogna881,

That is indeed a great idea. It is however already partly implemented in issue #48. Starting from v2.1.0 it will be possible to define your own file name[ output format](https://github.com/ytdl-org/youtube-dl/#output-template), so you can add the upload date yourself!

Closing the issue as this was already implemented,.

**Comment by bogna881** [comment]
cool, this is a very great project and much appreciative of you, thanks for creating it
