### ISSUE TITLE
how can I run on Solus?

### ISSUE THREAD

**Issue by tyty999** [jely2002/youtube-dl-gui#6]
how can I run on linux

**Comment by jely2002** [comment]
Hi tyty999,

Linux support is currently not there yet. Because of your request I will start testing on Linux, and if all goes right I will have a linux version for you in no-time!

**Comment by jely2002** [comment]
Linux support has been added in (c34e86e). The upcoming update will contain this feature (comes out in 1-2 days).
I will be closing the issue for now, feel free to contact me if you have any questions.
