### ISSUE TITLE
stuck on audio downloading

### ISSUE THREAD

**Issue by thaynos** [jely2002/youtube-dl-gui#60]
it has been stuck on audio downloading for the past 30 mins
![image](https://user-images.githubusercontent.com/83282129/117643260-432bf900-b199-11eb-9da1-d1c8274e1313.png)

**Comment by jely2002** [comment]
Hi thaynos,

Have you checked if the video has downloaded succesfully? It may just be a glitched progressbar.
If the video has downloaded succesfully I will not fix this, sometimes ytdl just does something unexpected, and I can't account for all the unexpected stuff.

**Comment by thaynos** [comment]
it did download eventually but it took almost half an hour jsut for audio download

**Comment by jely2002** [comment]
This most likely has nothing to do with my GUI because the download does eventually finish. This has more to do with youtube-dl itself. Closing the issue.

**Comment by jely2002** [comment]
Adding a little note to this issue. Today I noticed it sometimes gets hung up on "Downloading audio - 100%" if it's doing some merging or downloading subtitles in the background. So it is normal for this to happen, might at one point create a different progress status that shows "Finishing up" or something like that.
