### ISSUE TITLE
adding version number to icon?

### ISSUE THREAD

**Issue by thaynos** [jely2002/youtube-dl-gui#62]
it would be nice to see the version number on the icon jsut for ease of access.
something like this maybe
![Background](https://user-images.githubusercontent.com/83282129/118599209-3a05e200-b7c0-11eb-8fca-d9f7a5e75e04.png)

**Comment by jely2002** [comment]
I will not be adding this as I personally find it not matching the logo and not of use. The version number can be checked at anytime in the settings menu at the bottom left.
