### ISSUE TITLE
new update broke the app

### ISSUE THREAD

**Issue by thaynos** [jely2002/youtube-dl-gui#64]
theres literally no audio at all for the videos i downloaded using the new version.
could it be cuz of auto gen subtitles enabled?
i cant check because rn the youtubedl returned empty object bug is happening

**Comment by jely2002** [comment]
I can't replicate this issue. Maybe you selected the video only option? This option only downloads the video without the audio. If you want the video and the audio you must select video + audio.

Please let me know if this helped resolve your issue.

**Comment by jely2002** [comment]
About the youtube-dl returned empty object bug, please report the failed video to me and I will take a look at what is going wrong.

**Comment by thaynos** [comment]
> About the youtube-dl returned empty object bug, please report the failed video to me and I will take a look at what is going wrong.
its not just one video its my watch later playlist. i have given the cookies.txt files and everything. it just randomly stops working.

**Comment by thaynos** [comment]
> I can't replicate this issue. Maybe you selected the video only option? This option only downloads the video without the audio. If you want the video and the audio you must select video + audio.
> 
> Please let me know if this helped resolve your issue.

nope it dint fix my issue video+audio was always selected.

**Comment by jely2002** [comment]
Hi thaynos, I was able to replicate the issue now. Will investigate.

**Comment by jely2002** [comment]
I have now applied and released a fix for this problem in version 2.1.1.
Please let me know if the update fixed this issue.
