### ISSUE TITLE
Retry option on download failed

### ISSUE THREAD

**Issue by IshaanKr** [jely2002/youtube-dl-gui#66]
When download failed, there is no option to get the url of the failed video or there should be a retry button

**Comment by jely2002** [comment]
Hi IshaanKr,

This is a great idea and I can't believe I didn't think of it earlier. 
Will be adding this to the roadmap of v2.2.0

Please let me know if you have any additional questions.

**Comment by IshaanKr** [comment]
Nice!!

I think it would be better if there is an option of auto-retry of lets say "5 times"  (which can be changed by user or set to auto-retry until success)

When auto retry fails, there should be a retry button next to the video.

and In case, video cannot be downloaded (in-case youtube-dl doesn't support downloading from that url or else), it should give option to the user to get the url of that video. Because may be the user have entered all the urls and closed his all tabs of browser. Now, if youtube-dl-gui doesn't give URL, he/she will never be able to get that URL. (assuming going thru browser history every time would be a hassle)

**Comment by jely2002** [comment]
I don't think I will implement the auto-retry as I don't like the idea of stuff happening automatically. But I'll gladly add the retry button and a way to get the url from a failed video.

**Comment by jely2002** [comment]
I have added the functionality to retry failed/finished videos and playlist with the retry button. I have also enabled the info button for errored videos so it is possible to copy the URL from there.

This functionality will be visible to you at the next release.

**Comment by jely2002** [comment]
This has now been shipped in v2.2.0.
