### ISSUE TITLE
please add support for chiasenhac.vn

### ISSUE THREAD

**Issue by mohibo** [jely2002/youtube-dl-gui#67]
**Is your feature request related to a problem? Please describe.**
no its not related to a problem

**Describe the solution you'd like**
i would love to see support for chiasenhac.vn

**Describe alternatives you've considered**
there are no alternatives

**Additional context**

**Comment by jely2002** [comment]
Hi mohibo,

This app is just a graphical interface for youtube-dl. I can not add sites to youtube-dl. For this you need to be at [their repository](https://github.com/ytdl-org/youtube-dl/) as chiasenhac.vn is currently not on the list of supported sites.

If you happen to have more questions, please let me know.
