### ISSUE TITLE
Solution for error "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)"

### ISSUE THREAD

**Issue by edwinyzh** [jely2002/youtube-dl-gui#68]
When downloading videos from some sites you'll get the `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)` error, and with the command line the solution is to add the `--no-check-certificate` parameter.
How to do that with youtube-dl-gui? I guess an option should be added for this?

Thanks.

**Comment by jely2002** [comment]
Hi edwinzyh,
I have added this option in v2.1.2, by default --no-check-certificate is passed to youtube-dl. If this doesn't work for someone they could always turn it on again.
