### ISSUE TITLE
filename format template question

### ISSUE THREAD

**Issue by bogna881** [jely2002/youtube-dl-gui#69]
thanks for the update i am glad about the filename format addition, but can you please post a guide of what to put in, for example i want title channel name and date, what should i put into the format to get that, thank you!

**Comment by jely2002** [comment]
Hi bogna881,

I have now added the new settings to[ the settings wiki page](https://github.com/jely2002/youtube-dl-gui/wiki/Settings). On that page all settings are explained including the [new filename format](https://github.com/jely2002/youtube-dl-gui/wiki/Settings#filename-format). It also links to a tutorial and examples by youtube-dl itself.

Hope I helped you out, let me know if you have any additional questions.

**Comment by bogna881** [comment]
thank you, once again this is a very good project and appreciate your hardwork!
