### ISSUE TITLE
[Bug?] The videos doesn't have sound.

### ISSUE THREAD

**Issue by flopezre** [jely2002/youtube-dl-gui#70]
**Describe the bug**
Hello, the Videos doesn't have sound

**To Reproduce**
1. Download is complete
2. i'm use Movies and TV player from Windows 10
**Video**
https://streamable.com/qyverz

**Video Links**
1. https://www.youtube.com/watch?v=hyfJEukX2Mc (**ASMR**)
2. https://www.youtube.com/watch?v=Yk6pnWF84-A (**Astrix**)
3. https://www.youtube.com/watch?v=xdln9EFiu34 (**ASMR**)

**Comment by jely2002** [comment]
Hi Fabian,
I have looked into this. And the only way I can replicate this is by setting the output format to mp4. 

![image](https://user-images.githubusercontent.com/20154900/118946015-4cb21f80-b956-11eb-9eb1-ebd0554ca015.png)

This re-encodes the video into mp4, sadly the Movies and TV player can't play this type of mp4 encoding very well, so there is no sound. One of the ways to mitigate this is to set the output format to auto which will create a mkv file. Or to open the mp4 in VLC media player.

If you have anymore questions please let me know.

**Comment by flopezre** [comment]
Hello, i try download this video a work..
https://www.youtube.com/watch?v=ilVF1jXWSkM

Video ex:
https://streamable.com/wj0yw6

**Comment by flopezre** [comment]
I download the Astrix video (https://www.youtube.com/watch?v=Yk6pnWF84-A) with other app and works:

**Comment by jely2002** [comment]
This can potentially be fixed with the changes suggested in #47.
Adding this to the v2.3.0 milestone.

**Comment by jely2002** [comment]
As this can be fixed with #47 I will be closing this issue, as this issue will get resolved when I implement #47.
