### ISSUE TITLE
Save settings in the portable version too

### ISSUE THREAD

**Issue by klaids** [jely2002/youtube-dl-gui#71]
I try to change a setting and apply it but when I re-open the app all the setting turn to the default state.

 - OS: [e.g. Windows 10]
 - Application version [2.1.3 Portable]

**Comment by jely2002** [comment]
Hi klaids,

I will add a feature that saves your settings for the portable version as well. 
However I strongly recommend you use the installed version (e.g YouTube-Downloader-GUI-Setup-2.1.3.exe). This version comes with some benefits, it launches faster and it auto-updates to the most recent version.

If you happen to have any questions feel free to ask.

**Comment by thaynos** [comment]
yes please i asked for this too in #56

**Comment by jely2002** [comment]
I would still recommend you use the installer, because it's faster and easier :P

**Comment by thaynos** [comment]
no but the thing is im using a guest account and my admin wont allow me to download any external apps. so portable apps are the only way i can do anything without his perm

**Comment by jely2002** [comment]
Thanks for the clarification thaynos. It all makes sense to me now!

**Comment by jely2002** [comment]
This has been added and was shipped with v2.2.0.
