### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by trymeouteh** [jely2002/youtube-dl-gui#72]
I am very tech savvy and know to bookmark this github page and go to the releases to download the file I need for my operating system. But not everyone is tech savvy to download software from github easily

Maybe consider creating a simple website kinda like NewPipe did where someone can go to learn about YouTube Downloader GUI and download the app easily. The download sources should be from Github but with a easy URL link on the website

https://newpipe.net/

I like this app and I think by having a website, it will be easy for people to find and to download and use.

**Comment by thaynos** [comment]
idk if i would call downloading from releases or bookmarking is tech savvy but i see what you mean

**Comment by thaynos** [comment]
im pretty sure a website is in developemnt right now. ig he will be releasing it soon. you can see the progress in the projects tab.

**Comment by jely2002** [comment]
Oh shoot, the website was already done for some time now. I just forgot to add it to the README.
You can find it live here https://jely2002.github.io/youtube-dl-gui
By the way I won't be buying a custom domain for it, as I'm a cheap student. 

Closing the issue because the website already exists 😄
