### ISSUE TITLE
Unhandled exception any YouTube Video

### ISSUE THREAD

**Issue by speedingcheetah** [jely2002/youtube-dl-gui#76]
Installed this software on newly setup computer for my mother.
Win 10 fully updated.
It does not work at all for any youtube video downloads.
The same videos download fine on her old computer as well as mine.
What is wrong with this install?  
Both computers have ESET NOD32 antivirus installed,  but i tried disabling it on the new computer and did not affect this issue.
![Capture](https://user-images.githubusercontent.com/66632023/119204563-60937980-ba5b-11eb-8402-12d6b75a5f3f.PNG)

**Comment by jely2002** [comment]
Hi speedingcheetah,

I was able to reproduce this issue when I did not have the[ Visual C++ redistributable 2010](https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x86.exe) installed. Installing this redistributable fixed it on my side. Could you try to install this redistributable and see if it helps?

In future versions the installer will ask the user if it may install the redistributable automatically.

If you have any other questions please let me know and I'll be happy to fix this with you.

**Comment by speedingcheetah** [comment]
Install that fixed the issue. Thank you
