### ISSUE TITLE
language selector for subtitles

### ISSUE THREAD

**Issue by thaynos** [jely2002/youtube-dl-gui#77]
this is not what i meant by i want subs XD
![image](https://user-images.githubusercontent.com/83282129/119216956-f4128c00-bae7-11eb-8e43-efe33c5deaea.png)
maybe add an option for only select languages?
also i noticed theres a motherload of subtitles for EACH video
![image](https://user-images.githubusercontent.com/83282129/119216984-2c19cf00-bae8-11eb-89bb-e71057b15537.png)
isnt there a way to embed the subs or even give an option to hardcode?

**Comment by jely2002** [comment]
This has been added and released in v2.2.0.
