### ISSUE TITLE
duplicate video prompt

### ISSUE THREAD

**Issue by thaynos** [jely2002/youtube-dl-gui#79]
can you add a function in which if im downloading a duplicate video it would ask to replace or rename or even add an opt in setting to do either of those by default

**Comment by jely2002** [comment]
If a video has the same name as one already in the folder youtube-dl will skip the download and it will complete instantly. When a different name is used (it has another quality and that is shown in the name for example) it downloads the video normally. I don't see why I would want to ever overwrite or rename a duplicate video. I would just remove the old video in File Explorer and download the new video.

Closing this as I don't think this feature would be worth my time.

**Comment by thaynos** [comment]
no this is definetly not what is happening. instead of skipping this happens
![image](https://user-images.githubusercontent.com/83282129/119307342-9f544a00-bc7c-11eb-815d-83ce31606281.png)
it adds a .temp file for some reason
also this happens
![image](https://user-images.githubusercontent.com/83282129/119307415-b8f59180-bc7c-11eb-80be-4104b325c8d8.png)
for all of these downloads the settings were exact same there was no change in the naming format or file format
