### ISSUE TITLE
prompt to delete videos 

### ISSUE THREAD

**Issue by thaynos** [jely2002/youtube-dl-gui#80]
similar to #54 
when pressing the x it doesnt show any notification nothing really happens but when pressing twice it gets deleted
also then it still shows downloading in the bottom bar
![image](https://user-images.githubusercontent.com/83282129/119217558-0b537880-baec-11eb-9866-900d3185fccb.png)
also there should an option to delete from queue or from my pc completely 
i would rather have a popup screen asking where to delete from
or even an opt in setting for pop up or the subtle notification thats supposed to happen in the current version

**Comment by jely2002** [comment]
This behavior has now been fixed and will be released in v2.2.0.
