### ISSUE TITLE
download bar glitched

### ISSUE THREAD

**Issue by thaynos** [jely2002/youtube-dl-gui#82]
this happened after #80 
when i add a new thing to the queue when the queue is already downloading something the download bar changes to ready to download for some reason. after sometime it changes back to normal showing task completion. but if i delete this new thing it shows ready to downlaod again but blank.
![image](https://user-images.githubusercontent.com/83282129/119217955-c67d1100-baee-11eb-9f88-bc3a6d560916.png)
![image](https://user-images.githubusercontent.com/83282129/119217956-c9780180-baee-11eb-99a9-609813e11912.png)
![image](https://user-images.githubusercontent.com/83282129/119217957-cb41c500-baee-11eb-8b7f-78c98c7bfbbd.png)
also the playlist that is downloading and the new playlist is the exact same
i retried the download because i thought the download will stop if i remove it from the displayed queue (#80 )

**Comment by jely2002** [comment]
Due to the way the progress bar works this is expected behavior. And since it switches back to normal after a while I don't feel like patching it.
