### ISSUE TITLE
uncaught exception for traffic blocked by software firewall

### ISSUE THREAD

**Issue by hl2guide** [jely2002/youtube-dl-gui#84]
**Describe the bug**
An uncaught exception is thrown if the host PC is configured with a firewall in "block" mode.

**To Reproduce**
1. Have Firewall Software installed in "block" mode
2. Run youtube-dl-gui
3. Attempt a video download

**Expected behavior**
A nicer message in the app that recommends that user checks their internet connection or firewall settings.

**Additional info (please complete the following information):**
 - OS: Windows 10
 - Application version: v2.1.3

**Comment by jely2002** [comment]
Hi hl2guide,
I'll need some more info to add a nice error message. First of all could you please report the error to me so I know what the unhandled error message is and can detect it.

What firewall software are you using if I may ask?

**Comment by hl2guide** [comment]
I'm using: **simplewall**

Screenshot of the problem:

![example](https://user-images.githubusercontent.com/17044982/119869466-9ce73e00-bf63-11eb-9d08-e0bb07576d92.png)

**Comment by jely2002** [comment]
This has now been released in version 2.2.0.
