### ISSUE TITLE
Custom Download Folder - Show file in folder

### ISSUE THREAD

**Issue by hl2guide** [jely2002/youtube-dl-gui#85]
**Describe the bug**
Download folder is not set for "Show file in folder" button.

**To Reproduce**
1. Set the download folder to another folder than the default
2. Download a video
2. Once completed click the "Show file in folder", it opens the user folder instead (e.g. C:\Users\Dean) of the custom folder

**Expected behavior**
The custom download folder should open instead.

**Additional info (please complete the following information):**
- OS: Windows 10
- Application version: v2.1.3

**Comment by jely2002** [comment]
This bug should now be fixed. And the fix will be released in version 2.2.0.
