### ISSUE TITLE
Add terminal in app

### ISSUE THREAD

**Issue by trymeouteh** [jely2002/youtube-dl-gui#87]
Please add a button to toggle a terminal window and be able to use youtube-dl commands in the app. This app auto updates youtube-dl easily on all operating systems and therefore it would be very easy to have an up to date youtube-dl command line using this app.

**Comment by jely2002** [comment]
Guess I can add an option that opens the system terminal with its working directory set to the place where the youtube-dl binary is stored. But you do know that youtube-dl has its own updater that you can use with `youtube-dl -U`.

**Comment by trymeouteh** [comment]
I did not know youtube-dl can be easily updated with a simple command. Thanks you for pointing that out.

**Comment by jely2002** [comment]
I will be closing this issue. As using a terminal in this app defeats the purpose. You may as well use the actual terminal then.
