### ISSUE TITLE
Download video with channel URL

### ISSUE THREAD

**Issue by mohitmeanslove** [jely2002/youtube-dl-gui#90]
There is no option to download video with uploader's  channel URL and Channel name.

**Comment by jely2002** [comment]
I don't think I understand you. You can enter a channel URL and it will add all videos of that channel to the queue.
With channel URL I mean this: https://www.youtube.com/user/NoCopyrightSounds or https://www.youtube.com/channel/UC8AEj2uw4v50sG8IWrYjD0A.

**Comment by mohitmeanslove** [comment]
> I don't think I understand you. You can enter a channel URL and it will add all videos of that channel to the queue.
> With channel URL I mean this: https://www.youtube.com/user/NoCopyrightSounds or https://www.youtube.com/channel/UC8AEj2uw4v50sG8IWrYjD0A.

OKAY. Let me make you understand  . In other software like Mediahuman youtube downloader ,one can download video with **custom FILENAME** i.e Channel URL and Channel Name whose video you are downloading ,   but there is no option like this in Firedm.
If you still don't understand then check this screenshot. Hope it will make you understand.


1)**Screenshot of Free Youtube downloader by DVDVIDEOSOFT**

![DVDSOFT](https://user-images.githubusercontent.com/84594515/120201020-99450700-c242-11eb-8529-767cdea7a815.png)

2)**Screenshot of Youtube downloader by MEDIAHUMAN**

![mediahuman](https://user-images.githubusercontent.com/84594515/120201026-9a763400-c242-11eb-8f1e-d9291fbbb7ba.png)

**Comment by mohitmeanslove** [comment]
please open this issue.

**Comment by jely2002** [comment]
This is already possible see issue #69 for documentation on how to create your own filename templates.

**Comment by mohitmeanslove** [comment]
> This is already possible see issue #69 for documentation on how to create your own filename templates.
> If I answered your question please close the issue,

Thanks. This helps me a lot.
But i am facing one issue here.

I want to put this URL " https://www.youtube.com/channel " in filename but it always create a folder.
now what to do?

**Comment by jely2002** [comment]
![image](https://user-images.githubusercontent.com/20154900/120231102-f5168c80-c250-11eb-9b82-05b710c90794.png)
This is a limitation of windows that I can't do anything about.

**Comment by mohitmeanslove** [comment]
okay buddy. 
Thanks. Closed.
