### ISSUE TITLE
Add clipboard monitoring

### ISSUE THREAD

**Issue by mohitmeanslove** [jely2002/youtube-dl-gui#94]
Kindly add clipboard monitoring in the software so that whenever anyone copy youtube link . Software will automatically start downloading the video file without any prompt. This option is available in the other software as well..

Screenshot of byclick youtube downloader
![pp](https://user-images.githubusercontent.com/84594515/120233028-74688800-c272-11eb-9772-cacc8d29b88a.png)

**Comment by jely2002** [comment]
Oh no no, I will NEVER download videos automatically. What I can do is detect when a link is copied and show it in the box, so you only have to click on the `add` button, so you won't need to paste it.

**Comment by mohitmeanslove** [comment]
Hahahahaha. Being a developer, You should left this option to user whether he wants to download automatically or not. 
There are many other software which provides this like Mediahuman Youtube downloader. 

I still request you to provide this option. Rest it's all your wish

**Comment by jely2002** [comment]
Well first off all, with all the different video sites youtube-dl can download from. It is impossible to detect if it is a valid URL or not without trying it out. So this would make it that every URL you copy gets put into youtube-dl. I won't be doing that.

Secondly, I don't really feel that respected by you. I provide this app without any charge and maintain it in my free time, being laughed at, is something I'm not okay with. if you really want this feature you should use the other app you showed screenshots of.

>  What I can do is detect when a link is copied and show it in the box, so you only have to click on the add button, so you won't need to paste it.

Lastly, the above has now been implemented.

**Comment by mohitmeanslove** [comment]
My intention was not to disrespect you. 

Btw you can give this option that automatically download feature will work only on youtube links not on other website. Rest it's all ur wish. 

Yes, i will use other software. When u r downloading 10-12 youtube videos then it is difficult to press download button everytime.

Thank you.

**Comment by mohitmeanslove** [comment]
> Well first off all, with all the different video sites youtube-dl can download from. It is impossible to detect if it is a valid URL or not without trying it out. So this would make it that every URL you copy (even non video sites) gets put into youtube-dl. I won't be doing that.
> 
> Secondly, I don't really feel that respected by you. I provide this app without any charge and maintain it in my free time, being laughed at, is something I'm not okay with. if you really want this feature you should use the other app you showed screenshots of.
> 
> > What I can do is detect when a link is copied and show it in the box, so you only have to click on the add button, so you won't need to paste it.
> 
> Lastly, the above has now been implemented.

My intention was not to disrespect you. 

Btw you can give this option that automatically download feature will work only on youtube links not on other website. Rest it's all ur wish. 

Yes, i will use other software. When u r downloading 10-12 youtube videos then it is difficult to press download button everytime.

Thank you.
