### ISSUE TITLE
SponsorBlock Support

### ISSUE THREAD

**Issue by aaryanpednekarr** [jely2002/youtube-dl-gui#95]
Please Add SponsorBlock Support
Thank You!

**Comment by jely2002** [comment]
Hi Aaryan,
I didn't know of SponsorBlock before, but after having looked it up it looks quite cool. Sadly I won't be adding support, as this is not a feature of youtube-dl. It would require me to ship another binary to provide this support, such as SponSkrub. It would be better to use SponSkrub yourself after having downloaded the video.

Thanks for understanding.
