### ISSUE TITLE
Feature Request : MultiThread downloading , Filename template

### ISSUE THREAD

**Issue by mohitmeanslove** [jely2002/youtube-dl-gui#96]
List of features
1) **Multithread Downloading/ Connections per Download** : Kindly provide this option so that video will be download in fast way. This function has already been existed in [firedm](https://github.com/firedm/FireDM) whose developer is also on github.

Screenshot of " Connection per Download " in firedm Software 
![connections](https://user-images.githubusercontent.com/84594515/120714857-69675f00-c4e1-11eb-96e1-8e026bf61deb.png)

2)**Filename Template** :Please provide more options in filename format like channel id,uploader name etc . Though i know how to add filename in [custom filename](https://github.com/jely2002/youtube-dl-gui/wiki/Settings#filename-format)  but it would be easier to use if u add  more file templates in file format like it exist in Mediahuman Youtube downloader.

Screenshot of filename template  in Mediahuman Youtube downloader
![dds](https://user-images.githubusercontent.com/84594515/120716290-75ecb700-c4e3-11eb-9a12-fc7a9bb41a81.png)

3)**Thumbnail Issue** : Thumbnail always get download in Webp format. It should be in jpg or jpeg or Png like firedm software always download thumbnail in PNG.

4) **Download Automatically** : When a person copy a youtube Url then it should get download automatically without any prompt. As developer Jelly told me in some other thread that it is not possible for every website. Okay. No problem but atleast provide for youtube website.

5) **Try to use [Yt-dlp](https://github.com/yt-dlp/yt-dlp) in future updates** :  Though i am not an expert But as far as my little knowledge which i have , I found that Yt-dlp gives more options  and better than Youtube-dl. In the latest release of Yt-dlp, Developer has merged youtube-dl into yt-dlp. You can check the [release notes](https://github.com/yt-dlp/yt-dlp/releases/tag/2021.06.01)

Btw firedm software gives both options. You can use youtube_dl and Yt_dlp as per your wish.

![lls](https://user-images.githubusercontent.com/84594515/120720238-5d7f9b00-c4e9-11eb-813f-6c24896571d2.png)

**Comment by jely2002** [comment]
1. As far as I know the amount of connections is already maximised. Besides, this is a GUI for youtube-dl, which doesn't offer any options regarding connections. Lastly I don't feel there is a need to add this setting. As this application shouldn't get too advanced.

2. I won't be adding any extra templates as everyone has different ideas for what template they want to use. And I wont keep adding templates, while users can create templates themselves.

3. I am unable to replicate this issue, thumbnails get embedded just fine. And if I select the option to save as a separate file the thumbnail is saved as .jpg. Implementing conversion to jpg should be done by youtube-dl not this app. If you keep experiencing this please open up a separate issue with enough information for me to investigate/replicate the issue.

4. As I said before I will not be automatically downloading videos. I consider this unwanted behaviour. You can always enter comma separated URL's and the app will add all of them automatically, after adding you can then download the whole queue.

5. I will not be adding support for ytdlp as this is not needed, I don't need the more fancy features. This was discussed before in #20.

**Comment by mohitmeanslove** [comment]
> 1. As far as I know the amount of connections is already maximised. Besides, this is a GUI for youtube-dl, which doesn't offer any options regarding connections. Lastly I don't feel there is a need to add this setting. As this application shouldn't get too advanced.
> 2. I won't be adding any extra templates as everyone has different ideas for what template they want to use. And I wont keep adding templates, while users can create templates themselves.
> 3. I am unable to replicate this issue, thumbnails get embedded just fine. And if I select the option to save as a separate file the thumbnail is saved as .jpg. Implementing conversion to jpg should be done by youtube-dl not this app. If you keep experiencing this please open up a separate issue with enough information for me to investigate/replicate the issue.
> 4. As I said before I will not be automatically downloading videos. I consider this unwanted behaviour. You can always enter comma separated URL's and the app will add all of them automatically, after adding you can then download the whole queue.
> 5. I will not be adding support for ytdlp as this is not needed, I don't need the more fancy features. This was discussed before in #20.

1) I've seen software which is also based on youtube-dl but they provides option to change connections per download. May be you don't know coding to implement this feature so leave it. No problem. 

2)What is the problem in adding more file name templates? There are only two pre-defined templates. You are wrong here that everyone knows about it . People uses GUI over command line because they are not expert in in command line or coding. One need to learn little bit of coding to add custom file name template which is not possible for everyone. Anways Please remove that two pre-defined file name as well because as per you, everyone knows about it.

3)Many video editing software doesn't allow to import webp format whereas jpg or png is universal acceptable format by all software. This is why,  software like firedm, tomabo youtube downloader etc changes thumbnail format to jpg or png . As far as my knowledge, They uses ffmpeg to convert webp to jpg or png. I am not sure though. Anyways you don't want to provide it. No problem.

4)Suppose a person want to download 10-20 videos then as per you, he will add comma everytime .what a stupidity. Anyways you don't want to add this download automatically feature. No problem.

Thanks brother. You are really a good developer. Bye. Take care. God bless you.

Closed.
