### ISSUE TITLE
Playlist Index not working

### ISSUE THREAD

**Issue by boydfields** [jely2002/youtube-dl-gui#97]
I am using a custom file format:

%(playlist)s/%(playlist_index)s-%(title)s.%(ext)s

The playlist index is missing on all output files.  I have tried various filename formats, all with the same result.

I have tried using youtube-dl command line and it worked.

I'm assuming this is a bug?

Please advise.
Many thanks

**Comment by jely2002** [comment]
Playlist index will not work because under the hood my GUI downloads them as separate videos. This is because of performance reasons, for example it allows me to download multiple videos at the same time. This isn't possible when downloading as a playlist through youtube-dl.

**Comment by jely2002** [comment]
I will be fixing this by replacing the not working format strings with values, before sending them to ytdl.

**Comment by jely2002** [comment]
This issue has now been fixed and will be released in the next bug fix or feature update.

**Comment by boydfields** [comment]
Thank you @jely2002 much appreciated.
