### ISSUE TITLE
Change Default Download Directory

### ISSUE THREAD

**Issue by mattogrady87** [jely2002/youtube-dl-gui#99]
There doesn't appear to be an option to change the default download directory. This would be a nice ease-of-use feature. Thanks!

**Comment by jely2002** [comment]
Hi Matt,

This is already a feature and can be accessed by clicking on the folder icon in the bottom left corner of the app.
I should create a more clear tutorial of what all the buttons are for in the app.

![Screenshot 2021-06-06 201832](https://user-images.githubusercontent.com/20154900/120935740-7adc8100-c704-11eb-8e9a-818e17c0670d.png)

If you have any more questions feel free to ask.
